### ISSUE TITLE
StringOutOfBoundsException on Spring Boot's ApplicationContextAssert

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite#107]
This one is in spring boot. [ApplicationContextAssert](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-test/src/main/java/org/springframework/boot/test/context/assertj/ApplicationContextAssert.java) produces a string index out of bounds exception parsing an annotation.

> Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 20623, end 18717, length 21274
> 	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
> 	at java.base/java.lang.String.substring(String.java:1874)
> 	at org.openrewrite.java.Java11ParserVisitor.visitAnnotation(Java11ParserVisitor.java:101)

**Comment by jkschneider** [comment]
Fix in rewrite-java-8: https://github.com/openrewrite/rewrite-java-8/commit/c8e18f2c949e0a1b8147858c1ef387d5941c2a7a
