### ISSUE TITLE
Java Refactoring Recipe example does not work with Java 17

### ISSUE THREAD

**Issue by biergit** [openrewrite/rewrite#1164]
Running the test of https://docs.openrewrite.org/tutorials/writing-a-java-refactoring-recipe fails with Java 17 and Java compile target 8 as well as 11 using `rewrite-java-8` and `rewrite-java-11` respectively.

```
java.lang.IllegalAccessError: superclass access check failed: class 
org.openrewrite.java.Java11Parser$ByteArrayCapableJavacFileManager (in unnamed module @0x150c158) cannot access class com.sun.tools.javac.file.JavacFileManager (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.file to unnamed module @0x150c158

	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at org.openrewrite.java.JavaParser.fromJavaVersion(JavaParser.java:105)
	at org.openrewrite.samples.SayHelloRecipeTest.<init>(SayHelloRecipeTest.kt:8)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
```

**Comment by pway99** [comment]
Hi @biergit, 

There is a workaround running the build plugins on Java versions 16 and above; check out https://github.com/openrewrite/rewrite/issues/909.

```Starting with java 16, the default JVM behavior does not allow access to protected modules. The workaround for this issue is to add explicit exports for packages used by rewrite's java parser.```

I am going to close this one in favor of #909.

Thanks!

**Comment by pway99** [comment]
Hi @biergit,

I have updated the plugins to check for the necessary JVM-protected module exports and to log a message with instructions on configuring either the Maven or Gradle configuration if necessary.  

Also, I have updated the documentation as it turns out that Java 17 requires 3 additional module exports which were not documented.

Thanks again for raising this issue.
