### ISSUE TITLE
Support for JDK 17?

### ISSUE THREAD

**Issue by breandan** [openrewrite/rewrite#1254]
Does OpenRewrite plan to support later versions of Java? I am running the following recipe on `7.16.3` with JDK 17: 

```
import org.openrewrite.java.*

fun main() {
  val cus = JavaParser.fromJavaVersion()
    .build()
    .parse(
      """
      class Bar {}
      class B { static void foo(Bar a, Bar b, Bar c) {} }
      class Test {
         {  Bar a = Bar(); Bar b = Bar(); Bar c = Bar(); B.foo(a, b, c); }
      }
      """
    )

  val recipe = DeleteMethodArgument("B foo(Bar, Bar, Bar)", 1)

  recipe.run(cus).forEach { println(it.after.printAll()) }
}
```

However this produced the following error:

```
Exception in thread "main" java.lang.IllegalAccessError: superclass access check failed: class org.openrewrite.java.Java11Parser$ByteArrayCapableJavacFileManager (in unnamed module @0x6e8dacdf) cannot access class com.sun.tools.javac.file.JavacFileManager (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.file to unnamed module @0x6e8dacdf
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at org.openrewrite.java.JavaParser.fromJavaVersion(JavaParser.java:105)
	...
```

The [prerequisites](https://docs.openrewrite.org/getting-started/recipe-development-environment#prerequisites) only specify `1.8+`, but did not mention an upper bound. Thanks!

**Comment by pway99** [comment]
Hi @breandan,

Rewrite requires access to protected modules. The workaround for this issue is to add explicit exports for packages used by rewrite's java parser.

Add the following exports to your IDE's JVM run configurations when developing recipes.
```
--add-exports jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.jvm=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
```
The QuickStart documentation [execute-a-refactoring-recipe](https://docs.openrewrite.org/getting-started/getting-started#step-3-execute-a-refactoring-recipe) has instructions for configuring the plugins to run on Java 16 or later.

Thanks for bringing this to our attention I will update the docs.

**Comment by pway99** [comment]
https://github.com/openrewrite/rewrite-docs/commit/881b561bb1eac0e8fe9027aeb0d26cb93ccca68a
