### ISSUE TITLE
ChangeDependencyGroupIdAndArtifactId: SocketTimeoutException: connect timed out

### ISSUE THREAD

**Issue by josemariavillar** [openrewrite/rewrite#1325]
Good afternoon, 

Testing the **ChangeDependencyGroupIdAndArtifactId** recipe, I'm getting unit test failures. I get the following error: **Caused by: java.net.SocketTimeoutException: connect timed out**

This error occurs since version **7.17.0** and **7.17.1**. Please, can you tell me what can be happening and how to fix it.

I attach traces of the error:

```
rewrite.maven.resolve.dependency.management{}
    sum=7
    rate=12.336739/s
rewrite.maven.resolve.parents{}
    sum=10
    rate=17.433098/s
rewrite.maven.cache.size{content=metadata,type=inmem}
    value=0
rewrite.maven.cache.size{content=poms,type=inmem}
    value=33
rewrite.maven.cache.size{content=repository urls,type=inmem}
    value=1
rewrite.maven.download{exception=none,outcome=cached,repo.id=https://repo.maven.apache.org/maven2,type=pom}
    sum=24
    rate=41.799154/s
    mean=0.000229504s
    max=0.0008176s
rewrite.maven.download{exception=none,outcome=downloaded,repo.id=https://repo.maven.apache.org/maven2,type=pom}
    sum=33
    rate=57.187538/s
    mean=0.069293709s
    max=0.9040717s


java.lang.AssertionError: Failed to run parse sources or recipe

	at org.openrewrite.RecipeTest$DefaultImpls._get_executionContext_$lambda-0(RecipeTest.kt:36)
	at org.openrewrite.maven.internal.MavenPomDownloader.normalizeRepository(MavenPomDownloader.java:398)
	at org.openrewrite.maven.internal.MavenPomDownloader.getDistinctNormalizedRepositories(MavenPomDownloader.java:356)
	at org.openrewrite.maven.internal.MavenPomDownloader.download(MavenPomDownloader.java:248)
	at org.openrewrite.maven.internal.RawMavenResolver.lambda$processDependencies$1(RawMavenResolver.java:346)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.openrewrite.maven.internal.RawMavenResolver.processDependencies(RawMavenResolver.java:395)
	at org.openrewrite.maven.internal.RawMavenResolver.processTask(RawMavenResolver.java:130)
	at org.openrewrite.maven.internal.RawMavenResolver.resolve(RawMavenResolver.java:111)
	at org.openrewrite.maven.internal.RawMavenResolver.processParent(RawMavenResolver.java:435)
	at org.openrewrite.maven.internal.RawMavenResolver.processTask(RawMavenResolver.java:127)
	at org.openrewrite.maven.internal.RawMavenResolver.resolve(RawMavenResolver.java:111)
	at org.openrewrite.maven.internal.RawMavenResolver.processParent(RawMavenResolver.java:435)
	at org.openrewrite.maven.internal.RawMavenResolver.processTask(RawMavenResolver.java:127)
	at org.openrewrite.maven.internal.RawMavenResolver.resolve(RawMavenResolver.java:111)
	at org.openrewrite.maven.internal.RawMavenResolver.processParent(RawMavenResolver.java:435)
	at org.openrewrite.maven.internal.RawMavenResolver.processTask(RawMavenResolver.java:127)
	at org.openrewrite.maven.internal.RawMavenResolver.resolve(RawMavenResolver.java:111)
	at org.openrewrite.maven.internal.RawMavenResolver.resolve(RawMavenResolver.java:96)
	at org.openrewrite.maven.internal.RawMavenResolver.processDependencyManagement(RawMavenResolver.java:173)
	at org.openrewrite.maven.internal.RawMavenResolver.processTask(RawMavenResolver.java:128)
	at org.openrewrite.maven.internal.RawMavenResolver.resolve(RawMavenResolver.java:111)
	at org.openrewrite.maven.internal.RawMavenResolver.resolve(RawMavenResolver.java:96)
	at org.openrewrite.maven.internal.RawMavenResolver.processDependencyManagement(RawMavenResolver.java:173)
	at org.openrewrite.maven.internal.RawMavenResolver.processTask(RawMavenResolver.java:128)
	at org.openrewrite.maven.internal.RawMavenResolver.resolve(RawMavenResolver.java:111)
	at org.openrewrite.maven.internal.RawMavenResolver.processParent(RawMavenResolver.java:435)
	at org.openrewrite.maven.internal.RawMavenResolver.processTask(RawMavenResolver.java:127)
	at org.openrewrite.maven.internal.RawMavenResolver.resolve(RawMavenResolver.java:111)
	at org.openrewrite.maven.internal.RawMavenResolver.resolve(RawMavenResolver.java:96)
	at org.openrewrite.maven.internal.RawMavenResolver.processDependencyManagement(RawMavenResolver.java:173)
	at org.openrewrite.maven.internal.RawMavenResolver.processTask(RawMavenResolver.java:128)
	at org.openrewrite.maven.internal.RawMavenResolver.resolve(RawMavenResolver.java:111)
	at org.openrewrite.maven.internal.RawMavenResolver.resolve(RawMavenResolver.java:96)
	at org.openrewrite.maven.internal.RawMavenResolver.processDependencyManagement(RawMavenResolver.java:173)
	at org.openrewrite.maven.internal.RawMavenResolver.processTask(RawMavenResolver.java:128)
	at org.openrewrite.maven.internal.RawMavenResolver.resolve(RawMavenResolver.java:111)
	at org.openrewrite.maven.internal.RawMavenResolver.resolve(RawMavenResolver.java:96)
	at org.openrewrite.maven.internal.RawMavenResolver.resolve(RawMavenResolver.java:75)
	at org.openrewrite.maven.MavenParser.parseInputs(MavenParser.java:104)
	at org.openrewrite.Parser.parse(Parser.java:60)
	at org.openrewrite.RecipeTest$DefaultImpls.assertChangedBase(RecipeTest.kt:50)
	at org.openrewrite.maven.MavenRecipeTest$DefaultImpls.assertChanged(MavenRecipeTest.kt:75)
	at com.santander.darwin.migrationassistant.ChangeDependencyTest.assertChanged(ChangeDependencyTest.kt:8)
	at org.openrewrite.maven.MavenRecipeTest$DefaultImpls.assertChanged$default(MavenRecipeTest.kt:65)
	at com.santander.darwin.migrationassistant.ChangeDependencyTest.changeOnlyArtifactId(ChangeDependencyTest.kt:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at org.openrewrite.maven.internal.MavenPomDownloader.lambda$static$5e2b0580$1(MavenPomDownloader.java:69)
	at io.github.resilience4j.retry.Retry.lambda$decorateCheckedFunction$7bb28b04$1(Retry.java:187)
	at org.openrewrite.maven.internal.MavenPomDownloader.normalizeRepository(MavenPomDownloader.java:389)
	... 114 more
```

Thank you very much

**Comment by tkvangorder** [comment]
Hi @josemariavillar .

It looks like the maven parser is failing as it tries to parse the maven file you provide via the test harness. Can you share the test maven file? Also, are you behind a corporate firewall that may block access to external sites? 

I should have added some logic to report which repository URI failed. 

When resolving a dependency, rewrite will:

1. Parse any repos from the dependency's pom file (including its parents).
2. From that list, it will apply any credentials, mirror settings, and verify the repository is reachable. (One of these repositories is timing out)
3. In the case of a socket timeout, rewrite will cache a "null" result for one minute and should continue to move on with the maven resolution process.

To work around this problem, you could put a breakpoint here: 

https://github.com/openrewrite/rewrite/blob/main/rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java#L404

You are interested in the value of the original `repository.getUri()`, as this is the server that is causing the timeout.

 There are two things you could try: 
 
 - Define a mirror that maps problematic repository into a repository that can resolve the dependency. See [how to configure your mirrors settings here](https://maven.apache.org/guides/mini/guide-mirror-settings.html). You will do this in your `${user.home}/.m2/settings.xml` file. 
 - Or, since this is a test, you could try to eliminate the dependency that has the problematic repository.

**Comment by josemariavillar** [comment]
Good morning,

Attached is the test case that is failing, in this case it is the same as the one you use in the ChangeDependencyGroupIdAndArtifactId recipe: 

```
    @Test
    fun changeOnlyArtifactId() = assertChanged(
        recipe = ChangeDependencyGroupIdAndArtifactId(
            "org.openrewrite.recipe",
            "rewrite-testing-frameworks",
            "org.openrewrite.recipe",
            "rewrite-testing-frameworks-internal"
        ),
        before = """
            <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>com.mycompany.app</groupId>
                <artifactId>my-app</artifactId>
                <version>1</version>
                <dependencies>
                    <dependency>
                        <groupId>org.openrewrite.recipe</groupId>
                        <artifactId>rewrite-testing-frameworks</artifactId>
                        <version>1.13.1</version>
                    </dependency>
                </dependencies>
            </project>
        """,
        after = """
            <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>com.mycompany.app</groupId>
                <artifactId>my-app</artifactId>
                <version>1</version>
                <dependencies>
                    <dependency>
                        <groupId>org.openrewrite.recipe</groupId>
                        <artifactId>rewrite-testing-frameworks-internal</artifactId>
                        <version>1.13.1</version>
                    </dependency>
                </dependencies>
            </project>
        """
    )
```

If I try the test with rewrite-maven version 7.16.0 and rewrite-maven-plugin version 4.16.0 it works, but with the current versions it fails.

**Comment by tkvangorder** [comment]
@josemariavillar Sorry for the delay, we are actually in the process of refactoring how we do Maven resolution. This work will likely impact this issue and many others we have around Maven resolution. I will update this issue once we are closer to the completion of our Maven work.

**Comment by josemariavillar** [comment]
No worries, thank you very much for everything

**Comment by tkvangorder** [comment]
@josemariavillar Can you please retry this using the 7.18.0 release?

**Comment by sambsnyd** [comment]
I'm going to close this issue since we believe it to be fixed. @josemariavillar feel free to reopen, or reach out to us on [slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA), if you encounter this or other problems with latest openrewrite.
