### ISSUE TITLE
AssertionError in `org.openrewrite.java.tree.JavaType$Method#getDeclaringType()`

### ISSUE THREAD

**Issue by michel-zimmer** [openrewrite/rewrite#1362]
When running `rewriteRun` in Gradle with `rewrite-spring:4.15.0` the following exception is thrown:

```txt
java.lang.AssertionError
	at org.openrewrite.java.tree.JavaType$Method.getDeclaringType(JavaType.java:879)
	at org.openrewrite.java.MethodMatcher.matches(MethodMatcher.java:116)
	at org.openrewrite.java.search.UsesMethod.visitJavaSourceFile(UsesMethod.java:46)
	at org.openrewrite.java.search.UsesMethod.visitJavaSourceFile(UsesMethod.java:24)
	at org.openrewrite.java.tree.J$CompilationUnit.acceptJava(J.java:1198)
	at org.openrewrite.java.tree.J.accept(J.java:51)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:198)
	at org.openrewrite.RecipeScheduler.lambda$scheduleVisit$4(RecipeScheduler.java:187)
	at org.openrewrite.RecipeScheduler.lambda$mapAsync$0(RecipeScheduler.java:50)
	at org.openrewrite.scheduling.ForkJoinScheduler.lambda$schedule$0(ForkJoinScheduler.java:41)
```

This is the relevant code:
https://github.com/openrewrite/rewrite/blob/v7.17.2/rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java#L879

First observation: The assertion checks that the `declaringType` field is not `null`. But the corresponding constructor parameter is annotated with `@Nullable`.

Is this a bug or could there maybe be a problem with how the tooling is used?

**Comment by jkschneider** [comment]
This is a bug. It's only temporarily `@Nullable` while the instance is being built up during parsing, but should be non-null by the time it's accessed.

**Comment by sambsnyd** [comment]
@michel-zimmer while we are big fans of lombok and use it ourselves, the abstract syntax tree OpenRewrite produces isn't aware of annotation processors, and any methods/constructors/etc they may produce. 

We plan to support lombok and similar annotation processors, but this work has not yet begun.
Essentially what we have to do is take the AST from the Java compiler running without lombok, then use the type information from the Java compiler with lombok.

**Comment by michel-zimmer** [comment]
I see, no problem. I can imagine, that it's far from trivial to support annotation processors, that modify the AST without a standardized mechanism how AST manipulation works.

We will continue to use the delombok function as we are in the lucky position that Lombok is primarily used in our production code and we are using the JUnit 4 -> 5 rewrite which affects our test code as one would expect.

**Comment by sambsnyd** [comment]
Hi @michel-zimmer. I've removed the assertion. Maybe we'll put it back in once we can better support lombok. Utilities that work with types, like `MethodMatcher`, wont be able to do anything with the `null` declaring type, but they wont explode with an NPE. Your example shows that removing the assertion is less disruptive than keeping it.
