### ISSUE TITLE
Pin checkstyle version to 9.x version: 10 is not compatible with java8 anymore

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite#1451]
Discovered with https://github.com/murdos/OpenCyclos/runs/5485542530?check_suite_focus=true

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/puppycrawl/tools/checkstyle/api/CheckstyleException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at g.<init>(Unknown Source)
	at io.moderne.ingest.IngestActionApplication.main(Unknown Source)
```

**Comment by traceyyoshima** [comment]
@murdos thanks for letting us know! We'll pin the version shortly

**Comment by murdos** [comment]
https://github.com/murdos/OpenCyclos/runs/5515731331?check_suite_focus=true still fails. 
Is this expected because moderne ingest is not yet updated?

**Comment by murdos** [comment]
Last run is in success :+1: : https://github.com/murdos/OpenCyclos/actions/runs/1982600990
