### ISSUE TITLE
NPE in JavaSourceSet builder on empty source file set.

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite#1636]
cc / @fabapp2 

```
java.lang.NullPointerException
	at org.openrewrite.java.tree.JRightPadded.getElements(JRightPadded.java:102)
	at org.openrewrite.java.tree.J$Block.getStatements(J.java:705)
	at org.openrewrite.java.marker.JavaSourceSet.typesFrom(JavaSourceSet.java:136)
	at org.openrewrite.java.marker.JavaSourceSet.build(JavaSourceSet.java:65)
	at org.springframework.sbm.openrewrite.java.marker.JavaSourceSetTest.buildJavaSourceSet(JavaSourceSetTest.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExt
```

**Comment by jkschneider** [comment]
This is the generated stub that fails:
```java
abstract <T, K, S extends java.lang.invoke.ClassSpecializer<T, K, S>$SpeciesData> ClassSpecializer<T, K, S> t50
```
