### ISSUE TITLE
Avoid ConcurrentModificationException

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#1666]
```java

List<Integer> integers = Arrays.asList(1, 2, 3);

    for (Integer integer : integers) {
        integers.remove(1);
    }


Exception in thread "main" java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractList.remove(AbstractList.java:167)
	at Scratch.main(scratch_5.java:10)
```

**Comment by tkvangorder** [comment]
Detecting this pattern might be quite tricky.

**Comment by yeikel** [comment]
One more RSPEC that covers this similar problem : https://rules.sonarsource.com/java/RSPEC-5413
