### ISSUE TITLE
StackOverflowError in Validated$Both.iterator()

### ISSUE THREAD

**Issue by ZzetT** [openrewrite/rewrite#2089]
I get the following exception:
```java
Exception in thread "main" java.lang.StackOverflowError
	at java.lang.Iterable.spliterator(Iterable.java:101)
	at org.openrewrite.Validated$Both.iterator(Validated.java:321)
	at java.lang.Iterable.spliterator(Iterable.java:101)
	at org.openrewrite.Validated$Both.iterator(Validated.java:321)
	at java.lang.Iterable.spliterator(Iterable.java:101)
	at org.openrewrite.Validated$Both.iterator(Validated.java:321)
	at java.lang.Iterable.spliterator(Iterable.java:101)
	at org.openrewrite.Validated$Both.iterator(Validated.java:321)
	at java.lang.Iterable.spliterator(Iterable.java:101)
	at org.openrewrite.Validated$Both.iterator(Validated.java:321)
	at java.lang.Iterable.spliterator(Iterable.java:101)
```

I have a Recipe that needs to change ~1500 types:
```java
public class ChangeAllTypes extends Recipe
{

    @Override
    public String getDisplayName()
    {
        return "Convert all types";
    }

    @Override
    public String getDescription()
    {
        return  "Convert all types";
    }

    public ChangeAllTypes ()
    {
        for (Entry<String, String> entry : TypeMappingSingleton.getInstance().getMap().entrySet()) /* returns ~1500 type */
        {
            doNext(new ChangeType(entry.getKey(), entry.getValue(), Boolean.TRUE));
        }
    }
}
```

In the stracktrace I can see that from the maven plugin in [AbstractRewriteMojo.listResults()](https://github.com/openrewrite/rewrite-maven-plugin/blob/1f7e5671180d8a062eb1782176450e6aa513bd54/src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java#L185) it calls ` validated.stream().map(Validated::failures)` and in `Validated.failures()` the `spliterator()` gets called which results in a huge stack due to a deeply nested tree in `Validated$Both`.

**Comment by jkschneider** [comment]
@ZzetT Thanks for the report, and we'll fix this up. As a shorter workaround, have you discovered `ChangePackage` which may limit the number of recipes you have to add to the list and perform better?

**Comment by ZzetT** [comment]
@jkschneider thanks for the quick reply. Unfortunately the types have been moved to different packages.
But as a workaround, I created a ".mvn/jvm.config" file in my project with the arguments "-Xss4m" which increases the stack size. This seems to be fine for my use-case at least.
