### ISSUE TITLE
StringIndexOutOfBoundsException during JavaSourceSet.declarableFullyQualifiedName

### ISSUE THREAD

**Issue by nmck257** [openrewrite/rewrite#2091]
Reproducible with this jar: `com.sageserpent:americium_3:1.7.1`

```kotlin
class MyTest : RewriteTest {
    @Test
    fun foo() {
        JavaSourceSet.build("main", JavaParser.dependenciesFromClasspath("americium_3"), JavaTypeCache(), false) // throws
    }
}
```

Throws:
```text
java.lang.StringIndexOutOfBoundsException: begin 63, end 61, length 61
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4604)
	at java.base/java.lang.String.substring(String.java:2707)
	at java.base/java.lang.String.substring(String.java:2680)
	at org.openrewrite.java.marker.JavaSourceSet.declarableFullyQualifiedName(JavaSourceSet.java:216)
	at org.openrewrite.java.marker.JavaSourceSet.packagesToTypeDeclarations(JavaSourceSet.java:103)
	at org.openrewrite.java.marker.JavaSourceSet.build(JavaSourceSet.java:79)
	at MyTest.foo(MyTest.kt:10)
```

The exception occurs while processing this class: https://github.com/sageserpent-open/americium/blob/master/src/main/scala/com/sageserpent/americium/java/TrialsScaffolding.java#L220

...Which looks something like this (in case it changes):
```java
public interface TrialsScaffolding<Case,
        SupplySyntaxType extends TrialsScaffolding.SupplyToSyntax<Case>>
        extends TrialsFactoring<Case> {
// ...
    interface Tuple2Trials<Case1, Case2> extends
            TrialsScaffolding<Tuple2<Case1, Case2>,
                    Tuple2Trials.SupplyToSyntaxTuple2<Case1, Case2>> {
        <Case3> Tuple3Trials<Case1, Case2, Case3> and(
                Trials<Case3> thirdTrials);

        interface SupplyToSyntaxTuple2<Case1, Case2>
                extends SupplyToSyntax<Tuple2<Case1, Case2>> {
            void supplyTo(BiConsumer<Case1, Case2> biConsumer);
        }
    }
// ...
}
```

Debugging in `JavaSourceSet.declarableFullyQuualifiedName`, I see that this class yields these outer classes from ClassGraph:
```text
0: public abstract static interface com.sageserpent.americium.java.TrialsScaffolding$Tuple2Trials<Case1, Case2> extends com.sageserpent.americium.java.TrialsScaffolding<cyclops.data.tuple.Tuple2<Case1, Case2>, com.sageserpent.americium.java.TrialsScaffolding$Tuple2Trials$SupplyToSyntaxTuple2<Case1, Case2>>
1: public static final class com.sageserpent.americium.java.TrialsScaffolding$Tuple2Trials$
2: public abstract interface com.sageserpent.americium.java.TrialsScaffolding<Case, SupplySyntaxType extends com.sageserpent.americium.java.TrialsScaffolding$SupplyToSyntax<Case>> extends com.sageserpent.americium.java.TrialsFactoring<Case>
```

...which is odd? Specifically that middle element? Might be a quirk of declaring an interface which extends its own child interface?

**Comment by tkvangorder** [comment]
The class that is tripping up the SourceSet logic is essentially empty and is marked as "external". I added logic to skip the class if it's external and I am wondering if this is a side effect of this project mixing both Scala and Java?

**Comment by nmck257** [comment]
Maybe? Never used Scala myself. But, that fix sounds reasonable to me.
Thanks!
