### ISSUE TITLE
Container NPE

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite#2101]
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/1697736/182898146-2a348416-d219-4198-9cc3-a153fa0bd1bb.png">

**Comment by pway99** [comment]
full stack trace for reference:
```LOG
org.openrewrite.UncaughtVisitorException: java.lang.NullPointerException: Cannot invoke \"org.openrewrite.java.tree.JContainer.getBefore()\" because \"container\" is null
  at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:253)
  at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
  at org.openrewrite.java.JavaVisitor.visitEnumValue(JavaVisitor.java:545)
  at org.openrewrite.java.tree.J$EnumValue.acceptJava(J.java:1555)
  at org.openrewrite.java.tree.J.accept(J.java:55)
  at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
  at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
  at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1231)
  at org.openrewrite.java.JavaVisitor.lambda$visitEnumValueSet$12(JavaVisitor.java:560)
  at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:138)
  at org.openrewrite.internal.ListUtils.map(ListUtils.java:120)
  at org.openrewrite.internal.ListUtils.map(ListUtils.java:138)
  at org.openrewrite.java.JavaVisitor.visitEnumValueSet(JavaVisitor.java:560)
  at org.openrewrite.java.tree.J$EnumValueSet.acceptJava(J.java:1603)
  at org.openrewrite.java.tree.J.accept(J.java:55)
  at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
  at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
  at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1231)
  at org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:373)
  at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:138)
  at org.openrewrite.internal.ListUtils.map(ListUtils.java:120)
  at org.openrewrite.internal.ListUtils.map(ListUtils.java:138)
  at org.openrewrite.java.JavaVisitor.visitBlock(JavaVisitor.java:372)
  at org.openrewrite.java.tree.J$Block.acceptJava(J.java:740)
  at org.openrewrite.java.tree.J.accept(J.java:55)
  at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
  at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
  at org.openrewrite.java.JavaVisitor.visitClassDeclaration(JavaVisitor.java:453)
  at org.openrewrite.java.tree.J$ClassDeclaration.acceptJava(J.java:1064)
  at org.openrewrite.java.tree.J.accept(J.java:55)
  at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
  at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
  at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1231)
  at org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:373)
  at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:138)
  at org.openrewrite.internal.ListUtils.map(ListUtils.java:120)
  at org.openrewrite.internal.ListUtils.map(ListUtils.java:138)
  at org.openrewrite.java.JavaVisitor.visitBlock(JavaVisitor.java:372)
  at org.openrewrite.java.tree.J$Block.acceptJava(J.java:740)
  at org.openrewrite.java.tree.J.accept(J.java:55)
  at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
  at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
  at org.openrewrite.java.JavaVisitor.visitClassDeclaration(JavaVisitor.java:453)
  at org.openrewrite.java.tree.J$ClassDeclaration.acceptJava(J.java:1064)
  at org.openrewrite.java.tree.J.accept(J.java:55)
  at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
  at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
  at org.openrewrite.java.JavaVisitor.lambda$visitCompilationUnit$10(JavaVisitor.java:472)
  at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:138)
  at org.openrewrite.internal.ListUtils.map(ListUtils.java:120)
  at org.openrewrite.internal.ListUtils.map(ListUtils.java:138)
  at org.openrewrite.java.JavaVisitor.visitCompilationUnit(JavaVisitor.java:472)
  at org.openrewrite.java.JavaVisitor.visitJavaSourceFile(JavaVisitor.java:460)
  at org.openrewrite.java.tree.J$CompilationUnit.acceptJava(J.java:1299)
  at org.openrewrite.java.tree.J.accept(J.java:55)
  at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
  at io.moderne.serialization.TreeSerializer.lambda$readInternal$5(TreeSerializer.java:209) ~[moderne-ast-write-0.34.0.jar:na]
  at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:138)
  at org.openrewrite.internal.ListUtils.map(ListUtils.java:120)
  at org.openrewrite.internal.ListUtils.map(ListUtils.java:138)
  at io.moderne.serialization.TreeSerializer.readInternal(TreeSerializer.java:207) ~[moderne-ast-write-0.34.0.jar:na]
  at io.moderne.serialization.TreeSerializer.read(TreeSerializer.java:113) ~[moderne-ast-write-0.34.0.jar:na]
  at io.moderne.worker.sources.AbstractSourceFileLoader.lambda$deserialize$13(AbstractSourceFileLoader.java:246) ~[classes/:na]
  at reactor.core.publisher.MonoCallable.call(MonoCallable.java:92) ~[reactor-core-3.4.18.jar:3.4.18]
  at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:228) ~[reactor-core-3.4.18.jar:3.4.18]
  at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203) ~[reactor-core-3.4.18.jar:3.4.18]
  at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89) ~[reactor-core-3.4.18.jar:3.4.18]
  at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.onComplete(MonoSubscribeOn.java:162) ~[reactor-core-3.4.18.jar:3.4.18]
  at reactor.core.publisher.MonoUsing$MonoUsingSubscriber.onNext(MonoUsing.java:232) ~[reactor-core-3.4.18.jar:3.4.18]
  at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) ~[reactor-core-3.4.18.jar:3.4.18]
  at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854) ~[reactor-core-3.4.18.jar:3.4.18]
  at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854) ~[reactor-core-3.4.18.jar:3.4.18]
  at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181) ~[reactor-core-3.4.18.jar:3.4.18]
  at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.4.18.jar:3.4.18]
  at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.4.18.jar:3.4.18]
  at io.micrometer.core.instrument.internal.TimedCallable.call(TimedCallable.java:51) ~[micrometer-core-1.9.2.jar:1.9.2]
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
  at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
  at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]\nCaused by: java.lang.NullPointerException: Cannot invoke \"org.openrewrite.java.tree.JContainer.getBefore()\" because \"container\" is null
  at org.openrewrite.java.JavaVisitor.visitContainer(JavaVisitor.java:1279)
  at org.openrewrite.java.JavaVisitor.visitNewClass(JavaVisitor.java:941)
  at org.openrewrite.java.tree.J$NewClass.acceptJava(J.java:3887)
  at org.openrewrite.java.tree.J.accept(J.java:55)
  at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
  ... 80 common frames omitted\n




```

**Comment by tkvangorder** [comment]
This issue is likely a manifestation of missing Java 17 language features.

See [#1501](https://github.com/openrewrite/rewrite/issues/1501)

**Comment by greg-at-moderne** [comment]
- `spring-projects/spring-framework` no longer suffers from LST problems
- we have evolved far beyond providing support for Java 17

=> I bet this error is no longer relevant, thus closing the issue.
