### ISSUE TITLE
Javadoc parsing error in apache/giraph causes missing type attribution

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite#2147]
This project has a large number of parsing issues that appear to be centered on Javadoc parsing. 

A sampling of these errors, which really do not indicate root cause: 
```
JCCompilationUnit(sourceFile = /home/ubuntu/workspace/ingest/apache_giraph/giraph-core/target/munged/main/org/apache/giraph/comm/requests/SendWorkerDataRequest.java)
JCClassDecl(name = SendWorkerDataRequest, line = 39)
--- END PATH ---

[main] WARNING io.moderne.maven.ModerneAstMojo - Failed to convert for the following cursor stack:--- BEGIN PATH ---
JCCompilationUnit(sourceFile = /home/ubuntu/workspace/ingest/apache_giraph/giraph-core/target/munged/main/org/apache/giraph/comm/requests/SendWorkerDataRequest.java)
--- END PATH ---

[main] WARNING io.moderne.maven.ModerneAstMojo - 
[main] WARNING io.moderne.maven.ModerneAstMojo - Failed to convert for the following cursor stack:--- BEGIN PATH ---
JCCompilationUnit(sourceFile = /home/ubuntu/workspace/ingest/apache_giraph/giraph-core/target/munged/main/org/apache/giraph/writable/kryo/GiraphClassResolver.java)
JCClassDecl(name = GiraphClassResolver, line = 57)
--- END PATH ---

[main] WARNING io.moderne.maven.ModerneAstMojo - Failed to convert for the following cursor stack:--- BEGIN PATH ---
JCCompilationUnit(sourceFile = /home/ubuntu/workspace/ingest/apache_giraph/giraph-core/target/munged/main/org/apache/giraph/writable/kryo/GiraphClassResolver.java)
--- END PATH ---

[main] WARNING io.moderne.maven.ModerneAstMojo - 
[main] WARNING io.moderne.maven.ModerneAstMojo - Failed to convert for the following cursor stack:--- BEGIN PATH ---
JCCompilationUnit(sourceFile = /home/ubuntu/workspace/ingest/apache_giraph/giraph-core/target/munged/main/org/apache/giraph/job/GiraphConfigurationValidator.java)
JCClassDecl(name = GiraphConfigurationValidator, line = 55)
--- END PATH ---

[main] WARNING io.moderne.maven.ModerneAstMojo - Failed to convert for the following cursor stack:--- BEGIN PATH ---
JCCompilationUnit(sourceFile = /home/ubuntu/workspace/ingest/apache_giraph/giraph-core/target/munged/main/org/apache/giraph/job/GiraphConfigurationValidator.java)
--- END PATH ---
...

```

This issue can be debugged by publishing rewrite core and the rewrite plugin to maven local and then running: 

`mvndebug -e compile org.openrewrite.maven:rewrite-maven-plugin:4.32.0-SNAPSHOT:dryRun -DactiveRecipes=org.openrewrite.java.cleanup.CommonStaticAnalysis`

The root cause is a NPE in the Javadoc parser:

```
java.lang.NullPointerException
	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:403)
	at org.openrewrite.java.ReloadableJava8JavadocVisitor.visitReference(ReloadableJava8JavadocVisitor.java:533)
	at org.openrewrite.java.ReloadableJava8JavadocVisitor.visitLink(ReloadableJava8JavadocVisitor.java:445)
	at org.openrewrite.java.ReloadableJava8JavadocVisitor.visitLink(ReloadableJava8JavadocVisitor.java:45)
	at com.sun.tools.javac.tree.DCTree$DCLink.accept(DCTree.java:422)
	at com.sun.source.util.DocTreeScanner.scan(DocTreeScanner.java:77)
	at org.openrewrite.java.ReloadableJava8JavadocVisitor.visitDocComment(ReloadableJava8JavadocVisitor.java:291)
	at org.openrewrite.java.ReloadableJava8JavadocVisitor.visitDocComment(ReloadableJava8JavadocVisitor.java:45)
	at com.sun.tools.javac.tree.DCTree$DCDocComment.accept(DCTree.java:122)
	at com.sun.source.util.DocTreeScanner.scan(DocTreeScanner.java:77)
	at org.openrewrite.java.ReloadableJava8ParserVisitor.formatWithCommentTree(ReloadableJava8ParserVisitor.java:1937)
	at org.openrewrite.java.ReloadableJava8ParserVisitor.convert(ReloadableJava8ParserVisitor.java:1460)
	at org.openrewrite.java.ReloadableJava8ParserVisitor.convertAll(ReloadableJava8ParserVisitor.java:1513)
	at org.openrewrite.java.ReloadableJava8ParserVisitor.visitCompilationUnit(ReloadableJava8ParserVisitor.java:517)
	at org.openrewrite.java.ReloadableJava8ParserVisitor.visitCompilationUnit(ReloadableJava8ParserVisitor.java:69)
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:550)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
	at org.openrewrite.java.ReloadableJava8Parser.lambda$parseInputs$3(ReloadableJava8Parser.java:207)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.openrewrite.java.ReloadableJava8Parser.parseInputs(ReloadableJava8Parser.java:229)
```

**Comment by tkvangorder** [comment]
This happens in Java 11 as well: 

```
	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:383)
	at org.openrewrite.java.isolated.ReloadableJava11JavadocVisitor.visitReference(ReloadableJava11JavadocVisitor.java:573)
	at org.openrewrite.java.isolated.ReloadableJava11JavadocVisitor.visitLink(ReloadableJava11JavadocVisitor.java:475)
	at org.openrewrite.java.isolated.ReloadableJava11JavadocVisitor.visitLink(ReloadableJava11JavadocVisitor.java:45)
	at com.sun.tools.javac.tree.DCTree$DCLink.accept(DCTree.java:538)
	at com.sun.source.util.DocTreeScanner.scan(DocTreeScanner.java:79)
	at org.openrewrite.java.isolated.ReloadableJava11JavadocVisitor.visitDocComment(ReloadableJava11JavadocVisitor.java:291)
	at org.openrewrite.java.isolated.ReloadableJava11JavadocVisitor.visitDocComment(ReloadableJava11JavadocVisitor.java:45)
	at com.sun.tools.javac.tree.DCTree$DCDocComment.accept(DCTree.java:138)
	at com.sun.source.util.DocTreeScanner.scan(DocTreeScanner.java:79)
	at org.openrewrite.java.isolated.ReloadableJava11ParserVisitor.formatWithCommentTree(ReloadableJava11ParserVisitor.java:1956)
	at org.openrewrite.java.isolated.ReloadableJava11ParserVisitor.convert(ReloadableJava11ParserVisitor.java:1479)
	at org.openrewrite.java.isolated.ReloadableJava11ParserVisitor.convert(ReloadableJava11ParserVisitor.java:1508)
	at org.openrewrite.java.isolated.ReloadableJava11ParserVisitor.convertStatements(ReloadableJava11ParserVisitor.java:1617)
	at org.openrewrite.java.isolated.ReloadableJava11ParserVisitor.convertStatements(ReloadableJava11ParserVisitor.java:1599)
	at org.openrewrite.java.isolated.ReloadableJava11ParserVisitor.visitClass(ReloadableJava11ParserVisitor.java:473)
	at org.openrewrite.java.isolated.ReloadableJava11ParserVisitor.visitClass(ReloadableJava11ParserVisitor.java:72)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
	at org.openrewrite.java.isolated.ReloadableJava11ParserVisitor.convert(ReloadableJava11ParserVisitor.java:1479)
	at org.openrewrite.java.isolated.ReloadableJava11ParserVisitor.convertAll(ReloadableJava11ParserVisitor.java:1532)
	at org.openrewrite.java.isolated.ReloadableJava11ParserVisitor.visitCompilationUnit(ReloadableJava11ParserVisitor.java:519)
	at org.openrewrite.java.isolated.ReloadableJava11ParserVisitor.visitCompilationUnit(ReloadableJava11ParserVisitor.java:72)
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
	at org.openrewrite.java.isolated.ReloadableJava11Parser.lambda$parseInputs$0(ReloadableJava11Parser.java:178)
```

**Comment by tkvangorder** [comment]
This is actually because this project is using the `munge` plugin. This is a preprocessor for java and it ends up copying the original source files in `src` into `target/munge` and then again in `target/munge/munge`

We, of course, scoop all these duplicate files up and attempt to parse them all, which leads to invalid sybmols.

The solution for this specific project is to run with a profile that does not invoke the munge preprocessor.
