### ISSUE TITLE
JavaTemplate will generate invalid code when a substitude value is a string having a new-line char

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite#2234]
Discovered while fixing UseStringReplaceTest https://github.com/openrewrite/rewrite/commit/1381bdd11417d8e359f1140ea07eac58a5289646

```java
@Test
    fun stringSubstitutionWithEscapeChars() = rewriteRun(
        { spec ->
            spec.recipe(toRecipe {
                object : JavaVisitor<ExecutionContext>() {
                    var replaceAllMatcher = MethodMatcher("java.lang.String replaceAll(String, String)")
                    var template = JavaTemplate.builder({ cursor }, "#{any(java.lang.String)}.replace(#{}, #{any(java.lang.String)}")
                        .doBeforeParseTemplate { x: String? -> println(x) }
                        .build()

                    override fun visitMethodInvocation(method: J.MethodInvocation, p: ExecutionContext): J {
                        var mi = super.visitMethodInvocation(method, p) as J.MethodInvocation
                        if (replaceAllMatcher.matches(mi)) {
                            mi = mi.withTemplate(template, mi.getCoordinates().replace(),
                               mi.select, "hello\nworld", mi.arguments[1])
                        }
                        return mi
                    }
                }
            })
        },
        java("""
            class A {
                String s = "".replaceAll("\n","\r\n");
            }
        """,
            """
            class A {
                String s = "".replace("hello\nworld","\r\n");
            }
        """)
    )
```

```log
Caused by: org.openrewrite.RecipeRunException: java.lang.NullPointerException: Cannot invoke "org.openrewrite.java.tree.JRightPadded.getElement()" because "l" is null
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:253)
	at org.openrewrite.java.format.SpacesVisitor.visit(SpacesVisitor.java:1161)
	at org.openrewrite.java.format.SpacesVisitor.visit(SpacesVisitor.java:28)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:145)
	at org.openrewrite.java.format.AutoFormatVisitor.visit(AutoFormatVisitor.java:63)
	at org.openrewrite.java.JavaVisitor.autoFormat(JavaVisitor.java:92)
	at org.openrewrite.java.JavaVisitor.autoFormat(JavaVisitor.java:87)
	at org.openrewrite.java.JavaTemplate$2.maybeReplaceStatement(JavaTemplate.java:489)
	at org.openrewrite.java.JavaTemplate$2.visitMethodInvocation(JavaTemplate.java:462)
	at org.openrewrite.java.JavaTemplate$2.visitMethodInvocation(JavaTemplate.java:102)
	at org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3474)
	at org.openrewrite.java.tree.J.accept(J.java:60)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:145)
	at org.openrewrite.java.JavaTemplate.withTemplate(JavaTemplate.java:520)
	at org.openrewrite.java.JavaTemplate.withTemplate(JavaTemplate.java:42)
	at org.openrewrite.java.tree.J.withTemplate(J.java:87)
	at org.openrewrite.java.cleanup.UseStringReplace$UseStringReplaceVisitor.visitMethodInvocation(UseStringReplace.java:95)
	at org.openrewrite.java.cleanup.UseStringReplace$UseStringReplaceVisitor.visitMethodInvocation(UseStringReplace.java:71)
	at org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3474)
	at org.openrewrite.java.tree.J.accept(J.java:60)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
	at org.openrewrite.java.JavaVisitor.visitLeftPadded(JavaVisitor.java:1254)
	at org.openrewrite.java.JavaVisitor.visitVariable(JavaVisitor.java:1168)
	at org.openrewrite.java.tree.J$VariableDeclarations$NamedVariable.acceptJava(J.java:5258)
	at org.openrewrite.java.tree.J.accept(J.java:60)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
	at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
	at org.openrewrite.java.JavaVisitor.lambda$visitVariableDeclarations$27(JavaVisitor.java:888)
	at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:141)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:123)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:141)
	at org.openrewrite.java.JavaVisitor.visitVariableDeclarations(JavaVisitor.java:888)
	at org.openrewrite.java.tree.J$VariableDeclarations.acceptJava(J.java:5149)
	at org.openrewrite.java.tree.J.accept(J.java:60)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
	at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
	at org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
	at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:141)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:123)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:141)
	at org.openrewrite.java.JavaVisitor.visitBlock(JavaVisitor.java:366)
	at org.openrewrite.java.tree.J$Block.acceptJava(J.java:745)
	at org.openrewrite.java.tree.J.accept(J.java:60)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
	at org.openrewrite.java.JavaVisitor.visitClassDeclaration(JavaVisitor.java:447)
	at org.openrewrite.java.tree.J$ClassDeclaration.acceptJava(J.java:1069)
	at org.openrewrite.java.tree.J.accept(J.java:60)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
	at org.openrewrite.java.JavaVisitor.lambda$visitCompilationUnit$10(JavaVisitor.java:466)
	at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:141)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:123)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:141)
	at org.openrewrite.java.JavaVisitor.visitCompilationUnit(JavaVisitor.java:466)
	at org.openrewrite.java.JavaVisitor.visitJavaSourceFile(JavaVisitor.java:454)
	at org.openrewrite.java.tree.J$CompilationUnit.acceptJava(J.java:1351)
	at org.openrewrite.java.tree.J.accept(J.java:60)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
	at org.openrewrite.RecipeScheduler.lambda$scheduleVisit$5(RecipeScheduler.java:247)
	... 95 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.openrewrite.java.tree.JRightPadded.getElement()" because "l" is null
	at org.openrewrite.java.tree.JRightPadded.getElements(JRightPadded.java:102)
	at org.openrewrite.java.tree.JContainer.getElements(JContainer.java:86)
	at org.openrewrite.java.tree.J$MethodInvocation.getArguments(J.java:3437)
	at org.openrewrite.java.format.SpacesVisitor.visitMethodInvocation(SpacesVisitor.java:243)
	at org.openrewrite.java.format.SpacesVisitor.visitMethodInvocation(SpacesVisitor.java:28)
	at org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3474)
	at org.openrewrite.java.tree.J.accept(J.java:60)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
```

**Comment by pway99** [comment]
These types of transformations should be performed by directly modifying the J.Literal vs using the JavaTemplate
```java
.withArguments(ListUtils.mapFirst(invocation.getArguments(), arg -> ((J.Literal) arg)
        .withValue(unEscapedLiteral)
        .withValueSource(String.format("\"%s\"", StringEscapeUtils.escapeJava(unEscapedLiteral)))));
```
