### ISSUE TITLE
ChangePropertyKey - PatternSyntaxException in rare cases

### ISSUE THREAD

**Issue by nmck257** [openrewrite/rewrite#2387]
This test case:
```java
    @Test
    void doesNotBreakOnKeysWhichIncludeRegexSpecialCharacters() {
        rewriteRun(
          spec -> spec.recipe(new ChangePropertyKey("foo", "foo.bar", null, null, null)),
          yaml(
            """
            swagger:
              paths:
                /api/v1/business-objects/{id}:
                  verb: GET
            """
          )
        );
    }
```

...yields "Failed to parse sources or run recipe", with this base exception:

```
Caused by: java.util.regex.PatternSyntaxException: Illegal repetition near index 42
swagger\.paths\./api/v1/business-objects/{key}\.verb
                                          ^
	at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
	at java.base/java.util.regex.Pattern.closure(Pattern.java:3309)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2214)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
	at java.base/java.lang.String.replaceFirst(String.java:2898)
	at org.openrewrite.yaml.ChangePropertyKey$ChangePropertyKeyVisitor.childMatchesNewPropertyKey(ChangePropertyKey.java:168)
	at org.openrewrite.yaml.ChangePropertyKey$ChangePropertyKeyVisitor.visitMappingEntry(ChangePropertyKey.java:119)
	at org.openrewrite.yaml.ChangePropertyKey$ChangePropertyKeyVisitor.visitMappingEntry(ChangePropertyKey.java:102)
```

**Comment by nmck257** [comment]
@pway99 thanks! Can probably close my PR #2388, then.

That said, my code used `Pattern.quote(cursorPropertyKey)`, which might be a simpler implementation

**Comment by pway99** [comment]
@nmck257 sorry I did not notice your PR for this one.  I agree Pattern.quote is a simpler solution, I'll revert my change and merge #2388
