### ISSUE TITLE
HCL: Parse error on module use with qualified provider configuration names

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite#2421]
As documented in the [Terraform documentation](https://developer.hashicorp.com/terraform/language/modules/develop/providers#passing-providers-explicitly) a module can be used with a map of providers where the provider names in the module have an alias:
```hcl
module "tunnel" {
  source    = "./tunnel"
  providers = {
    aws.src = aws.usw1
    aws.dst = aws.usw2
  }
}
```
The module would look something like this:
```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 2.7.0"
      configuration_aliases = [ aws.src, aws.dst ]
    }
  }
}
```
Currently this gives a parser error, because the parser doesn't like the qualified name on the left hand side in the `providers` block (i.e. it doesn't expect the dot in `aws.src` and `aws.dst`):
```
Caused by: org.openrewrite.hcl.HclParsingException: Syntax error in file.tf at line 4:7 no viable alternative at input '{\n    aws.'.
	at app//org.openrewrite.hcl.HclParser$ForwardingErrorListener.syntaxError(HclParser.java:118)
	... 128 more
Caused by: org.antlr.v4.runtime.NoViableAltException
	at app//org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2028)
	at app//org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:467)
	at app//org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:393)
	at app//org.openrewrite.hcl.internal.grammar.HCLParser.expression(HCLParser.java:582)
	... 123 more
```

**Comment by timtebeek** [comment]
- https://github.com/openrewrite/rewrite/pull/5967
