### ISSUE TITLE
Compact record constructors not working properly

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite#2455]
When I in the OpenRewrite Git repo add a test with a [compact record constructor](https://docs.oracle.com/en/java/javase/14/language/records.html#GUID-6699E26F-4A9B-4393-A08B-1E47D4B2D263__GUID-3677B517-B179-4891-BA52-45CB774E7250) like the following:

```java
public class RecordTest implements RewriteTest {

    @Test
    void javaRecord() {
        rewriteRun(
          java(
            """
                  public record JavaRecord(String name, @Deprecated int age) {
                    public JavaRecord {
                        java.util.Objects.requireNonNull(name);
                    }
                  }
              """
          )
        );
    }

}
```

The test fails, because it expects:
```java
public record JavaRecord(String name, @Deprecated int age) {
  public JavaRecord {
      java.util.Objects.requireNonNull(Stringname,int age) {
  public JavaRecord {
      java.util.Objects.requireNonNull(name);
  }
}
```

This looks rather strange. I didn't analyze it any further.

**Comment by knutwannheden** [comment]
This test fails with another error, but I suspect it has the same root cause:
```java
    @Test
    void javaRecord_2() {
        rewriteRun(
          java(
            """
                  public record Expression(String nested) {
                    public Expression {
                        java.util.Objects.requireNonNull(nested);
                    }
                  }
              """
          )
        );
    }
```
The exception being logged is:
```
Caused by: java.lang.StringIndexOutOfBoundsException: begin 120, end 117, length 117
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4601)
	at java.base/java.lang.String.substring(String.java:2704)
	at java.base/java.lang.String.substring(String.java:2677)
	at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitCompilationUnit(ReloadableJava17ParserVisitor.java:565)
	at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitCompilationUnit(ReloadableJava17ParserVisitor.java:71)
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:614)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at org.openrewrite.java.isolated.ReloadableJava17Parser.lambda$parseInputs$0(ReloadableJava17Parser.java:178)
	... 116 more
```

**Comment by traceyyoshima** [comment]
Hi @knutwannheden, I've started looking into the parsing issue, and it'll take a day or two to resolve.

Java 17 introduced flags related to `record`(s) in the compiler we aren't handling yet.
