### ISSUE TITLE
Do not reprocess dependencyManagement imports found in parents

### ISSUE THREAD

**Issue by nmck257** [openrewrite/rewrite#2504]
test case:
```java
    @Test
    void resolveDependencyManagementImportsOnlyOnce() {
        rewriteRun(
          pomXml("""
                <?xml version="1.0" encoding="UTF-8"?>
                <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
                  <modelVersion>4.0.0</modelVersion>
                
                  <parent>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-parent</artifactId>
                    <version>2.7.5</version>
                  </parent>
                
                  <groupId>org.sample</groupId>
                  <artifactId>sample</artifactId>
                  
                  <properties>
                    <mockito.version>3.9.0</mockito.version> <!-- mockito-bom did not exist prior to 4.x -->
                  </properties>
                  
                  <dependencyManagement>
                    <dependencies>
                      <dependency>
                        <groupId>org.mockito</groupId>
                        <artifactId>mockito-bom</artifactId>
                        <version>4.6.1</version>
                      </dependency>
                    </dependencies>
                  </dependencyManagement>
                </project>
                """)
        );
    }
```

This test fails during parsing with:

> org.openrewrite.maven.UncheckedMavenDownloadingException: Failed to download dependencies for pom.xml:
> [...]
> Caused by: org.openrewrite.maven.MavenDownloadingExceptions
>	at org.openrewrite.maven.MavenDownloadingExceptions.append(MavenDownloadingExceptions.java:44)
>	at org.openrewrite.maven.UncheckedMavenDownloadingException.<init>(UncheckedMavenDownloadingException.java:32)
>	... 75 more
>	Suppressed: org.openrewrite.maven.MavenDownloadingException: Unable to download POM. Tried repositories:
> [...]

And the `MavenDownloadingException`'s `failedAt` is `org.mockito:mockito-bom:3.9.0`.

For context, `spring-boot-dependencies` 2.7.5 contains this:
```xml
<dependencyManagement>
  <dependencies>
  ...
      <dependency>
        <groupId>org.mockito</groupId>
        <artifactId>mockito-bom</artifactId>
        <version>${mockito.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
  ...
  </dependencies>
</dependencyManagement>
```

Meanwhile, Maven can produce a `dependency:tree` for the pom in the test case without issue.

The difference seems to be that Maven remembers that it processed `org.mockito:mockito-bom` already in the project pom, and therefore does not reprocess it when it encounters it in the parent chain in `spring-boot-dependencies`. Rewrite *does* attempt to reprocess that dependency during `resolveParentdependenciesRecursively`, and because the requested GAV does not actually exist once you inject the version property from the project pom, we get an exception which fails the whole parse.

(Realistically, someone with a pom like this should refactor away from such a pattern, but I've seen it happen in the wild)

**Comment by timtebeek** [comment]
Thanks! Great to have this as a runnable test; confirmed to still happen in
- https://github.com/openrewrite/rewrite/pull/6569

**Comment by nmck257** [comment]
closing based on learnings in #6569
