### ISSUE TITLE
JavaTemplate fails when adding an import to the Builder

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite#256]
```
c = c.withTemplate(template("extends MyClass").imports("com.mycompany.MyClass").build(), c.getCoordinates().replaceExtendsClause());
```

```
Caused by: java.lang.ClassCastException: class org.openrewrite.Cursor cannot be cast to class org.openrewrite.ExecutionContext (org.openrewrite.Cursor and org.openrewrite.ExecutionContext are in unnamed module of loader 'app')
	at org.openrewrite.java.OrderImports$OrderImportsVisitor.visitCompilationUnit(OrderImports.java:58)
	at org.openrewrite.java.tree.J$CompilationUnit.acceptJava(J.java:1061)
	at org.openrewrite.java.tree.J.accept(J.java:58)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:131)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:144)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:144)
	at org.openrewrite.java.JavaPrinter.visit(JavaPrinter.java:65)
	at org.openrewrite.java.internal.template.JavaTemplatePrinter.visit(JavaTemplatePrinter.java:66)
	at org.openrewrite.java.internal.template.JavaTemplatePrinter.visit(JavaTemplatePrinter.java:33)
	at org.openrewrite.java.JavaPrinter.print(JavaPrinter.java:52)
	at org.openrewrite.java.JavaTemplate.withTemplate(JavaTemplate.java:96)
	```

**Comment by gadams00** [comment]
applies to staticImports as well.
