### ISSUE TITLE
`ClassCastException` in `ReplaceConstant` recipe

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite#2576]
The following test fails with a `ClassCastException` (see stacktrace below):
```java
    @Test
    void replaceStaticallyImportedConstant() {
        rewriteRun(
          spec -> spec.parser(JavaParser.fromJavaVersion().classpath("guava")),
          java(
            """
              import static com.google.common.base.Charsets.UTF_8;
              class Test {
                  Object o = UTF_8;
                  void foo() {
                      System.out.println(UTF_8);
                  }
              }
              """,
            """
              class Test {
                  Object o = "UTF_8";
                  void foo() {
                      System.out.println("UTF_8");
                  }
              }
              """
          )
        );
    }
```

Error:
```
Failed to parse sources or run recipe
java.lang.AssertionError: Failed to parse sources or run recipe
	at org.openrewrite.test.RewriteTest.lambda$defaultExecutionContext$10(RewriteTest.java:482)
	at org.openrewrite.test.RewriteTest$$Lambda$453/0x0000000800e27988.accept(Unknown Source)
	at org.openrewrite.RecipeScheduler.lambda$scheduleVisit$4(RecipeScheduler.java:226)
	at org.openrewrite.RecipeScheduler$$Lambda$629/0x0000000800f47d48.apply(Unknown Source)
	at org.openrewrite.RecipeScheduler.lambda$mapAsync$0(RecipeScheduler.java:53)
	at org.openrewrite.RecipeScheduler$$Lambda$630/0x0000000800f4c000.call(Unknown Source)
	at org.openrewrite.scheduling.DirectScheduler.schedule(DirectScheduler.java:35)
	at org.openrewrite.RecipeScheduler.mapAsync(RecipeScheduler.java:54)
	at org.openrewrite.RecipeScheduler.scheduleVisit(RecipeScheduler.java:183)
	at org.openrewrite.test.RecipeSchedulerCheckingExpectedCycles.scheduleVisit(RecipeSchedulerCheckingExpectedCycles.java:48)
	at org.openrewrite.RecipeScheduler.scheduleRun(RecipeScheduler.java:96)
	at org.openrewrite.Recipe.run(Recipe.java:303)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:309)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:121)
	at org.openrewrite.java.ReplaceConstantTest.replaceStaticallyImportedConstant(ReplaceConstantTest.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor$$Lambda$222/0x0000000800d121f8.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall$$Lambda$223/0x0000000800d12608.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$$Lambda$392/0x0000000800d40488.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor$$Lambda$404/0x0000000800d42b20.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$325/0x0000000800d31e08.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$324/0x0000000800d31be8.invoke(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$323/0x0000000800d317d0.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$329/0x0000000800d328f8.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$325/0x0000000800d31e08.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$324/0x0000000800d31be8.invoke(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$323/0x0000000800d317d0.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$329/0x0000000800d328f8.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$325/0x0000000800d31e08.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$324/0x0000000800d31be8.invoke(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$323/0x0000000800d317d0.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator$$Lambda$278/0x0000000800d1e888.accept(Unknown Source)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: org.openrewrite.internal.RecipeRunException: java.lang.ClassCastException: class org.openrewrite.java.tree.J$CompilationUnit cannot be cast to class org.openrewrite.java.tree.J$VariableDeclarations (org.openrewrite.java.tree.J$CompilationUnit and org.openrewrite.java.tree.J$VariableDeclarations are in unnamed module of loader 'app')
	at app//org.openrewrite.TreeVisitor.visit(TreeVisitor.java:326)
	at app//org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:358)
	at app//org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1261)
	at app//org.openrewrite.java.JavaVisitor.lambda$visitContainer$33(JavaVisitor.java:1314)
	at app//org.openrewrite.java.JavaVisitor$$Lambda$674/0x0000000800f5b1b0.apply(Unknown Source)
	at app//org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:141)
	at app//org.openrewrite.internal.ListUtils$$Lambda$625/0x0000000800f3a000.apply(Unknown Source)
	at app//org.openrewrite.internal.ListUtils.map(ListUtils.java:123)
	at app//org.openrewrite.internal.ListUtils.map(ListUtils.java:141)
	at app//org.openrewrite.java.JavaVisitor.visitContainer(JavaVisitor.java:1314)
	at app//org.openrewrite.java.JavaVisitor.visitMethodInvocation(JavaVisitor.java:855)
	at app//org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3644)
	at app//org.openrewrite.java.tree.J.accept(J.java:64)
	at app//org.openrewrite.TreeVisitor.visit(TreeVisitor.java:278)
	at app//org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:358)
	at app//org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1261)
	at app//org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:366)
	at app//org.openrewrite.java.JavaVisitor$$Lambda$638/0x0000000800f4da68.apply(Unknown Source)
	at app//org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:141)
	at app//org.openrewrite.internal.ListUtils$$Lambda$625/0x0000000800f3a000.apply(Unknown Source)
	at app//org.openrewrite.internal.ListUtils.map(ListUtils.java:123)
	at app//org.openrewrite.internal.ListUtils.map(ListUtils.java:141)
	at app//org.openrewrite.java.JavaVisitor.visitBlock(JavaVisitor.java:365)
	at app//org.openrewrite.java.tree.J$Block.acceptJava(J.java:756)
	at app//org.openrewrite.java.tree.J.accept(J.java:64)
	at app//org.openrewrite.TreeVisitor.visit(TreeVisitor.java:278)
	at app//org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:358)
	at app//org.openrewrite.java.JavaVisitor.visitMethodDeclaration(JavaVisitor.java:816)
	at app//org.openrewrite.java.tree.J$MethodDeclaration.acceptJava(J.java:3386)
	at app//org.openrewrite.java.tree.J.accept(J.java:64)
	at app//org.openrewrite.TreeVisitor.visit(TreeVisitor.java:278)
	at app//org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:358)
	at app//org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1261)
	at app//org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:366)
	at app//org.openrewrite.java.JavaVisitor$$Lambda$638/0x0000000800f4da68.apply(Unknown Source)
	at app//org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:141)
	at app//org.openrewrite.internal.ListUtils$$Lambda$625/0x0000000800f3a000.apply(Unknown Source)
	at app//org.openrewrite.internal.ListUtils.map(ListUtils.java:123)
	at app//org.openrewrite.internal.ListUtils.map(ListUtils.java:141)
	at app//org.openrewrite.java.JavaVisitor.visitBlock(JavaVisitor.java:365)
	at app//org.openrewrite.java.tree.J$Block.acceptJava(J.java:756)
	at app//org.openrewrite.java.tree.J.accept(J.java:64)
	at app//org.openrewrite.TreeVisitor.visit(TreeVisitor.java:278)
	at app//org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:358)
	at app//org.openrewrite.java.JavaVisitor.visitClassDeclaration(JavaVisitor.java:453)
	at app//org.openrewrite.java.tree.J$ClassDeclaration.acceptJava(J.java:1195)
	at app//org.openrewrite.java.tree.J.accept(J.java:64)
	at app//org.openrewrite.TreeVisitor.visit(TreeVisitor.java:278)
	at app//org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:358)
	at app//org.openrewrite.java.JavaVisitor.lambda$visitCompilationUnit$10(JavaVisitor.java:472)
	at app//org.openrewrite.java.JavaVisitor$$Lambda$633/0x0000000800f4c6d0.apply(Unknown Source)
	at app//org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:141)
	at app//org.openrewrite.internal.ListUtils$$Lambda$625/0x0000000800f3a000.apply(Unknown Source)
	at app//org.openrewrite.internal.ListUtils.map(ListUtils.java:123)
	at app//org.openrewrite.internal.ListUtils.map(ListUtils.java:141)
	at app//org.openrewrite.java.JavaVisitor.visitCompilationUnit(JavaVisitor.java:472)
	at app//org.openrewrite.java.JavaVisitor.visitJavaSourceFile(JavaVisitor.java:460)
	at app//org.openrewrite.java.tree.J$CompilationUnit.acceptJava(J.java:1498)
	at app//org.openrewrite.java.tree.J.accept(J.java:64)
	at app//org.openrewrite.TreeVisitor.visit(TreeVisitor.java:278)
	at app//org.openrewrite.RecipeScheduler.lambda$scheduleVisit$4(RecipeScheduler.java:222)
	... 113 more
Caused by: java.lang.ClassCastException: class org.openrewrite.java.tree.J$CompilationUnit cannot be cast to class org.openrewrite.java.tree.J$VariableDeclarations (org.openrewrite.java.tree.J$CompilationUnit and org.openrewrite.java.tree.J$VariableDeclarations are in unnamed module of loader 'app')
	at org.openrewrite.java.ReplaceConstant$1.isVariableDeclaration(ReplaceConstant.java:87)
	at org.openrewrite.java.ReplaceConstant$1.visitIdentifier(ReplaceConstant.java:73)
	at org.openrewrite.java.ReplaceConstant$1.visitIdentifier(ReplaceConstant.java:58)
	at org.openrewrite.java.tree.J$Identifier.acceptJava(J.java:2352)
	at org.openrewrite.java.tree.J.accept(J.java:64)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:278)
	... 173 more

```
The cause appears to be a change in `90b2f3d5d83fbfef3836b7d48646cc4ceba1b226` on lines 86 and 87 as the type of the `maybeVariable` can also be `J.CompilationUnit`: https://github.com/openrewrite/rewrite/blob/ca3ec0f9ebfd5e97e504b272f495377db4a0b759/rewrite-java/src/main/java/org/openrewrite/java/ReplaceConstant.java#L85-L87

**Comment by tkvangorder** [comment]
Thanks for reporting Knut!

**Comment by knutwannheden** [comment]
@tkvangorder I hope you haven't already put work into this. I could have mentioned that I had a fix in the works. If you have a better way to fix this, don't hesitate to close my PR.

Please note that I added a test case for a yet uncovered corner case. I can file a separate issue for that.
