### ISSUE TITLE
NullPointerException while visiting lambda

### ISSUE THREAD

**Issue by hetzijzo** [openrewrite/rewrite#2886]
When I run OpenRewrite against my project, I get a NullPointerException

```
[WARNING] Exception while visiting project file 'libraries\bsp-core\src\main\java\nl\devolksbank\bsp\core\identity\IdentityContext.java (in IdentityContext.isA)', caused by: java.lang.NullPointerException, at org.openrewrite.java.internal.template.Substitutions.lambda$substitute$0(Substitutions.java:117)
[DEBUG] 

org.openrewrite.internal.RecipeRunException: Exception while visiting project file 'libraries\bsp-core\src\main\java\nl\devolksbank\bsp\core\identity\IdentityContext.java (in IdentityContext.isA)', caused by: java.lang.NullPointerException, at org.openrewrite.java.internal.template.Substitutions.lambda$substitute$0(Substitutions.java:117)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:324)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:356)
	at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1268)
	at org.openrewrite.java.JavaVisitor.visitMethodInvocation(JavaVisitor.java:849)
	at org.openrewrite.java.JavaIsoVisitor.visitMethodInvocation(JavaIsoVisitor.java:230)
	at nl.devolksbank.bsp.v4.identity.UpdateIdentityContextGetIdentityRecipe$UpdateGetIdentityVisitor.visitMethodInvocation(UpdateIdentityContextGetIdentityRecipe.java:71)
	at nl.devolksbank.bsp.v4.identity.UpdateIdentityContextGetIdentityRecipe$UpdateGetIdentityVisitor.visitMethodInvocation(UpdateIdentityContextGetIdentityRecipe.java:40)
	at org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3665)
	at org.openrewrite.java.tree.J.accept(J.java:64)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:356)
	at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1268)
	at org.openrewrite.java.JavaVisitor.visitMethodInvocation(JavaVisitor.java:849)
	at org.openrewrite.java.JavaIsoVisitor.visitMethodInvocation(JavaIsoVisitor.java:230)
	at nl.devolksbank.bsp.v4.identity.UpdateIdentityContextGetIdentityRecipe$UpdateGetIdentityVisitor.visitMethodInvocation(UpdateIdentityContextGetIdentityRecipe.java:71)
	at nl.devolksbank.bsp.v4.identity.UpdateIdentityContextGetIdentityRecipe$UpdateGetIdentityVisitor.visitMethodInvocation(UpdateIdentityContextGetIdentityRecipe.java:40)
	at org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3665)
	at org.openrewrite.java.tree.J.accept(J.java:64)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:356)
	at org.openrewrite.java.JavaVisitor.visitReturn(JavaVisitor.java:1015)
	at org.openrewrite.java.JavaIsoVisitor.visitReturn(JavaIsoVisitor.java:276)
	at org.openrewrite.java.JavaIsoVisitor.visitReturn(JavaIsoVisitor.java:31)
	at org.openrewrite.java.tree.J$Return.acceptJava(J.java:4613)
	at org.openrewrite.java.tree.J.accept(J.java:64)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:356)
	at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1268)
	at org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
	at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:145)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:126)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:145)
	at org.openrewrite.java.JavaVisitor.visitBlock(JavaVisitor.java:366)
	at org.openrewrite.java.JavaIsoVisitor.visitBlock(JavaIsoVisitor.java:94)
	at org.openrewrite.java.JavaIsoVisitor.visitBlock(JavaIsoVisitor.java:31)
	at org.openrewrite.java.tree.J$Block.acceptJava(J.java:761)
	at org.openrewrite.java.tree.J.accept(J.java:64)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:356)
	at org.openrewrite.java.JavaVisitor.visitMethodDeclaration(JavaVisitor.java:817)
	at org.openrewrite.java.JavaIsoVisitor.visitMethodDeclaration(JavaIsoVisitor.java:225)
	at org.openrewrite.java.JavaIsoVisitor.visitMethodDeclaration(JavaIsoVisitor.java:31)
	at org.openrewrite.java.tree.J$MethodDeclaration.acceptJava(J.java:3407)
	at org.openrewrite.java.tree.J.accept(J.java:64)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:356)
	at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1268)
	at org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
	at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:145)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:126)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:145)
	at org.openrewrite.java.JavaVisitor.visitBlock(JavaVisitor.java:366)
	at org.openrewrite.java.JavaIsoVisitor.visitBlock(JavaIsoVisitor.java:94)
	at org.openrewrite.java.JavaIsoVisitor.visitBlock(JavaIsoVisitor.java:31)
	at org.openrewrite.java.tree.J$Block.acceptJava(J.java:761)
	at org.openrewrite.java.tree.J.accept(J.java:64)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:356)
	at org.openrewrite.java.JavaVisitor.visitClassDeclaration(JavaVisitor.java:454)
	at org.openrewrite.java.JavaIsoVisitor.visitClassDeclaration(JavaIsoVisitor.java:114)
	at org.openrewrite.java.JavaIsoVisitor.visitClassDeclaration(JavaIsoVisitor.java:31)
	at org.openrewrite.java.tree.J$ClassDeclaration.acceptJava(J.java:1211)
	at org.openrewrite.java.tree.J.accept(J.java:64)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:356)
	at org.openrewrite.java.JavaVisitor.lambda$visitCompilationUnit$10(JavaVisitor.java:473)
	at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:145)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:126)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:145)
	at org.openrewrite.java.JavaVisitor.visitCompilationUnit(JavaVisitor.java:473)
	at org.openrewrite.java.JavaIsoVisitor.visitCompilationUnit(JavaIsoVisitor.java:119)
	at org.openrewrite.java.JavaIsoVisitor.visitCompilationUnit(JavaIsoVisitor.java:31)
	at org.openrewrite.java.JavaVisitor.visitJavaSourceFile(JavaVisitor.java:461)
	at org.openrewrite.java.JavaIsoVisitor.visitJavaSourceFile(JavaIsoVisitor.java:39)
	at org.openrewrite.java.JavaIsoVisitor.visitJavaSourceFile(JavaIsoVisitor.java:31)
	at org.openrewrite.java.tree.J$CompilationUnit.acceptJava(J.java:1514)
	at org.openrewrite.java.tree.J.accept(J.java:64)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
	at org.openrewrite.RecipeScheduler.lambda$scheduleVisit$4(RecipeScheduler.java:270)
	at org.openrewrite.RecipeScheduler.lambda$mapAsync$0(RecipeScheduler.java:56)
	at org.openrewrite.scheduling.ForkJoinScheduler.lambda$schedule$0(ForkJoinScheduler.java:41)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NullPointerException: null
	at org.openrewrite.java.internal.template.Substitutions.lambda$substitute$0(Substitutions.java:117)
	at org.openrewrite.internal.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:90)
	at org.openrewrite.internal.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:64)
	at org.openrewrite.java.internal.template.Substitutions.substitute(Substitutions.java:47)
	at org.openrewrite.java.JavaTemplate.withTemplate(JavaTemplate.java:63)
	at org.openrewrite.java.JavaTemplate.withTemplate(JavaTemplate.java:39)
	at org.openrewrite.java.tree.J.withTemplate(J.java:91)
	at nl.devolksbank.bsp.v4.identity.UpdateIdentityContextGetIdentityRecipe$UpdateGetIdentityVisitor.visitMethodInvocation(UpdateIdentityContextGetIdentityRecipe.java:75)
	at nl.devolksbank.bsp.v4.identity.UpdateIdentityContextGetIdentityRecipe$UpdateGetIdentityVisitor.visitMethodInvocation(UpdateIdentityContextGetIdentityRecipe.java:40)
	at org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3665)
	at org.openrewrite.java.tree.J.accept(J.java:64)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
	... 86 common frames omitted
```

**Comment by timtebeek** [comment]
Hi Willem; would you mind sharing the relevant code snippet in `IdentityContext.isA` ?
And do you have a bit more information about the steps taken in `UpdateIdentityContextGetIdentityRecipe$UpdateGetIdentityVisitor` ?
And I take it you're already on the latest versions (and [potentially snapshots](https://docs.openrewrite.org/reference/snapshot-instructions))?

**Comment by hetzijzo** [comment]
Yes I was on the latest release (not a snapshot).

Below is the snippet of the method within `IdentityContext`
```
private boolean isA(IdentityType type) {
  return getIdentity()
      .map(identity -> identity.getType() == type || identity.getType().getParent() == type)
      .orElse(false);
}
```

**Comment by timtebeek** [comment]
[A similar issue in the same recipe](https://github.com/openrewrite/rewrite/commit/68fc6fdad0ce05b2558bd7c0ddc61b9bd93efe52) was fixed yesterday; while your case seems different, perhaps it can be a starting point for the fix here as well. Is there anything more to `IdentityType` that would help turn this into a complete `rewriteRun` unit test?

**Comment by hetzijzo** [comment]
I see the `IdentityType.getParent()` is a generated lombok method.

**Comment by timtebeek** [comment]
I'm going to close this one as we at this point both lack the details to replicate this, seeing how the custom recipe visitor is no longer accessible.
