### ISSUE TITLE
MavenParser issue with submodules

### ISSUE THREAD

**Issue by oberkem** [openrewrite/rewrite#294]
MavenParser fails to parse submodules where dependencies don't have versions, but the dependency version would be inherited from the bom in parent pom. 

We are using openrewrite **v6.1.21**

Here is a test to replicate the issue on `6.x` branch:

```
@Test
    fun parseWithSubmodule() {
        val bom = """
            <project>
                <modelVersion>4.0.0</modelVersion>
            
                <groupId>com.mycompany.app</groupId>
                <artifactId>bom</artifactId>
                <version>1</version>
                <packaging>pom</packaging>
                
                <dependencyManagement>
                    <dependencies>
                        <dependency>
                            <groupId>com.google.guava</groupId>
                            <artifactId>guava</artifactId>
                            <version>30.0-jre</version>
                            <scope>import</scope>
                            <type>pom</type>
                        </dependency>
                    </dependencies>
                </dependencyManagement>
            </project>
        """.trimIndent()

        val parentPom = """
            <project>
                <modelVersion>4.0.0</modelVersion>
            
                <groupId>com.mycompany.app</groupId>
                <artifactId>my-app</artifactId>
                <version>1</version>
                
                <modules>
                    <module>submodule</module>
                </modules>

                <dependencyManagement>
                    <dependencies>
                        <dependency>
                            <groupId>com.mycompany</groupId>
                            <artifactId>bom</artifactId>
                            <version>1</version>
                            <type>pom</type>
                            <scope>import</scope>
                        </dependency>
                    </dependencies>
                </dependencyManagement>
            </project>
        """.trimIndent()

        val submodulePom = """
            <project>
                <modelVersion>4.0.0</modelVersion>
            
                <parent>
                    <groupId>com.mycompany.app</groupId>
                    <artifactId>my-app</artifactId>
                    <version>1</version>
                </parent>
                
                <artifactId>submodule</artifactId>

                <dependencies>
                  <dependency>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                  </dependency>
                </dependencies>
            </project>
        """.trimIndent()

        val parser = MavenParser.builder().build()
        parser.parse(bom, parentPom, submodulePom)
    }
```

which fails with:
```
Failed to determine version for com.google.guava:guava. Initial value was null. Including POM is at 74398901089211
org.openrewrite.maven.internal.MavenParsingException: Failed to determine version for com.google.guava:guava. Initial value was null. Including POM is at 74398901089211
	at org.openrewrite.maven.internal.RawMavenResolver.lambda$processDependencies$7(RawMavenResolver.java:333)
	at org.openrewrite.maven.internal.RawMavenResolver$$Lambda$452/0x000000080040a040.run(Unknown Source)
	at org.openrewrite.maven.internal.RawMavenResolver.doesThrow(RawMavenResolver.java:157)
	at org.openrewrite.maven.internal.RawMavenResolver.lambda$processDependencies$8(RawMavenResolver.java:290)
	at org.openrewrite.maven.internal.RawMavenResolver$$Lambda$446/0x0000000800408440.apply(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.openrewrite.maven.internal.RawMavenResolver.processDependencies(RawMavenResolver.java:393)
	at org.openrewrite.maven.internal.RawMavenResolver.processTask(RawMavenResolver.java:132)
	at org.openrewrite.maven.internal.RawMavenResolver._resolve(RawMavenResolver.java:113)
	at org.openrewrite.maven.internal.RawMavenResolver.resolve(RawMavenResolver.java:101)
	at org.openrewrite.maven.internal.RawMavenResolver.resolve(RawMavenResolver.java:84)
```

Note that this is **not** an issue in master branch or version 7 RCs.

It seems similar to [an issue already fixed](https://github.com/openrewrite/rewrite/issues/124), but the test cases were not aligned. 

Wondering if this issue will be fixed for version 6.x. 

If we need to migrate to 7.x, is there any updated docs? We are relying on `Change`, `Refactor`, `MavenRefactorVisitor` along with some Xml functionality that seems to be removed.

**Comment by jkschneider** [comment]
Can we talk about what is most expedient -- feel free to DM me on [Slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-lxaw3wap-6hzsYWyomw~Yrkx2hg~zZg). It would be some effort to backport to 6.x but willing to do it if you are under deadline pressure to deliver some remediation. Otherwise, happy to give you a walkthrough of the 7.x line and some of the reasoning there while we get docs moved over.

**Comment by oberkem** [comment]
Could you invite me to your Slack? Will be happy to chat

We are currently getting around this by using `.continueOnError(true)` which is obviously not ideal as it can mask other failures that we care about.

Either option would work for us. 6.x support would be ideal since we don't have to refactor to 7.x. I am not sure how much of an effort it would be to refactor our code to 7.x

**Comment by jkschneider** [comment]
Sure, this link allows you to join: https://join.slack.com/t/rewriteoss/shared_invite/zt-lxaw3wap-6hzsYWyomw~Yrkx2hg~zZg
