### ISSUE TITLE
error: `StringIndexOutOfBoundsException` from recipe `ReplaceLambdaWithMethodReference`

### ISSUE THREAD

**Issue by kunli2** [openrewrite/rewrite#2958]
This is an error from SAAS daily running from the recipe `ReplaceLambdaWithMethodReference`

![Screen Shot 2023-03-09 at 8 13 18 PM](https://user-images.githubusercontent.com/122563761/224256854-4d70134c-3c04-4450-a4da-9342cfc20d97.png)

This test can reproduce the error
```java
    @Test
    void stringIndexOutOfBoundsException() {
        rewriteRun(
          java(
            """
              import java.util.Collection;
              class A {
                  Collection<?> test(Object value) {
                      if (value instanceof Collection<?> values && values.stream().allMatch(it -> it instanceof Class)) {
                          return values;
                      }
                      return null;
                  }
              }
              """
          )
        );
    }
```

trace stack:
```
java.lang.AssertionError: Failed to parse sources or run recipe

    at org.openrewrite.test.RewriteTest.lambda$defaultExecutionContext$11(RewriteTest.java:511)
    at org.openrewrite.RecipeScheduler.lambda$scheduleVisit$3(RecipeScheduler.java:249)
    at org.openrewrite.RecipeScheduler.lambda$mapAsync$0(RecipeScheduler.java:58)
    at org.openrewrite.scheduling.DirectScheduler.schedule(DirectScheduler.java:35)
    at org.openrewrite.RecipeScheduler.mapAsync(RecipeScheduler.java:59)
    at org.openrewrite.RecipeScheduler.scheduleVisit(RecipeScheduler.java:210)
    at org.openrewrite.test.RecipeSchedulerCheckingExpectedCycles.scheduleVisit(RecipeSchedulerCheckingExpectedCycles.java:55)
    at org.openrewrite.RecipeScheduler.scheduleRun(RecipeScheduler.java:106)
    at org.openrewrite.Recipe.run(Recipe.java:418)
    at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:319)
    at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:128)
    at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:123)
    at org.openrewrite.java.cleanup.ReplaceLambdaWithMethodReferenceTest.test(ReplaceLambdaWithMethodReferenceTest.java:897)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
    at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
    at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
    at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
    at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
    at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
    at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
    at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
    at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
    at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
    at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
    at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
    at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
    at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
    at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
    at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
    at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
    at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
    at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
    at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
    at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
    at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
    at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
    at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.openrewrite.internal.RecipeRunException: Exception while visiting project file 'A.java (in A.test)', caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 52, at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4602)
    at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:324)
    at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:172)
    at org.openrewrite.java.JavaTemplate.withTemplate(JavaTemplate.java:107)
    at org.openrewrite.java.JavaTemplate.withTemplate(JavaTemplate.java:39)
    at org.openrewrite.java.tree.J.withTemplate(J.java:91)
    at org.openrewrite.java.cleanup.ReplaceLambdaWithMethodReference$1.visitLambda(ReplaceLambdaWithMethodReference.java:114)
    at org.openrewrite.java.cleanup.ReplaceLambdaWithMethodReference$1.visitLambda(ReplaceLambdaWithMethodReference.java:65)
    at org.openrewrite.java.tree.J$Lambda.acceptJava(J.java:2974)
    at org.openrewrite.java.tree.J.accept(J.java:64)
    at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
    at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:356)
    at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1274)
    at org.openrewrite.java.JavaVisitor.lambda$visitContainer$33(JavaVisitor.java:1327)
    at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:145)
    at org.openrewrite.internal.ListUtils.map(ListUtils.java:126)
    at org.openrewrite.internal.ListUtils.map(ListUtils.java:145)
    at org.openrewrite.java.JavaVisitor.visitContainer(JavaVisitor.java:1327)
    at org.openrewrite.java.JavaVisitor.visitMethodInvocation(JavaVisitor.java:862)
    at org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3700)
    at org.openrewrite.java.tree.J.accept(J.java:64)
    at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
    at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:356)
    at org.openrewrite.java.JavaVisitor.visitBinary(JavaVisitor.java:350)
    at org.openrewrite.java.tree.J$Binary.acceptJava(J.java:634)
    at org.openrewrite.java.tree.J.accept(J.java:64)
    at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
    at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:356)
    at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1274)
    at org.openrewrite.java.JavaVisitor.visitControlParentheses(JavaVisitor.java:502)
    at org.openrewrite.java.tree.J$ControlParentheses.acceptJava(J.java:4503)
    at org.openrewrite.java.tree.J.accept(J.java:64)
    at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
    at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:356)
    at org.openrewrite.java.JavaVisitor.visitIf(JavaVisitor.java:670)
    at org.openrewrite.java.tree.J$If.acceptJava(J.java:2426)
    at org.openrewrite.java.tree.J.accept(J.java:64)
    at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
    at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:356)
    at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1274)
    at org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
    at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:145)
    at org.openrewrite.internal.ListUtils.map(ListUtils.java:126)
    at org.openrewrite.internal.ListUtils.map(ListUtils.java:145)
    at org.openrewrite.java.JavaVisitor.visitBlock(JavaVisitor.java:366)
    at org.openrewrite.java.tree.J$Block.acceptJava(J.java:761)
    at org.openrewrite.java.tree.J.accept(J.java:64)
    at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
    at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:356)
    at org.openrewrite.java.JavaVisitor.visitMethodDeclaration(JavaVisitor.java:823)
    at org.openrewrite.java.tree.J$MethodDeclaration.acceptJava(J.java:3442)
    at org.openrewrite.java.tree.J.accept(J.java:64)
    at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
    at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:356)
    at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1274)
    at org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
    at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:145)
    at org.openrewrite.internal.ListUtils.map(ListUtils.java:126)
    at org.openrewrite.internal.ListUtils.map(ListUtils.java:145)
    at org.openrewrite.java.JavaVisitor.visitBlock(JavaVisitor.java:366)
    at org.openrewrite.java.tree.J$Block.acceptJava(J.java:761)
    at org.openrewrite.java.tree.J.accept(J.java:64)
    at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
    at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:356)
    at org.openrewrite.java.JavaVisitor.visitClassDeclaration(JavaVisitor.java:454)
    at org.openrewrite.java.tree.J$ClassDeclaration.acceptJava(J.java:1211)
    at org.openrewrite.java.tree.J.accept(J.java:64)
    at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
    at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:356)
    at org.openrewrite.java.JavaVisitor.lambda$visitCompilationUnit$10(JavaVisitor.java:473)
    at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:145)
    at org.openrewrite.internal.ListUtils.map(ListUtils.java:126)
    at org.openrewrite.internal.ListUtils.map(ListUtils.java:145)
    at org.openrewrite.java.JavaVisitor.visitCompilationUnit(JavaVisitor.java:473)
    at org.openrewrite.java.JavaVisitor.visitJavaSourceFile(JavaVisitor.java:461)
    at org.openrewrite.java.tree.J$CompilationUnit.acceptJava(J.java:1514)
    at org.openrewrite.java.tree.J.accept(J.java:64)
    at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
    at org.openrewrite.RecipeScheduler.lambda$scheduleVisit$3(RecipeScheduler.java:245)
    ... 81 more
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 52
    at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4602)
    at java.base/java.lang.String.substring(String.java:2705)
    at org.openrewrite.java.internal.template.BlockStatementTemplateGenerator.template(BlockStatementTemplateGenerator.java:408)
    at org.openrewrite.java.internal.template.BlockStatementTemplateGenerator.template(BlockStatementTemplateGenerator.java:467)
    at org.openrewrite.java.internal.template.BlockStatementTemplateGenerator.template(BlockStatementTemplateGenerator.java:467)
    at org.openrewrite.java.internal.template.BlockStatementTemplateGenerator.template(BlockStatementTemplateGenerator.java:467)
    at org.openrewrite.java.internal.template.BlockStatementTemplateGenerator.lambda$template$0(BlockStatementTemplateGenerator.java:82)
    at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:65)
    at org.openrewrite.java.internal.template.BlockStatementTemplateGenerator.template(BlockStatementTemplateGenerator.java:69)
    at org.openrewrite.java.internal.template.JavaTemplateParser.parseBlockStatements(JavaTemplateParser.java:158)
    at org.openrewrite.java.internal.template.JavaTemplateJavaExtension$1.maybeReplaceStatement(JavaTemplateJavaExtension.java:447)
    at org.openrewrite.java.internal.template.JavaTemplateJavaExtension$1.visitLambda(JavaTemplateJavaExtension.java:266)
    at org.openrewrite.java.internal.template.JavaTemplateJavaExtension$1.visitLambda(JavaTemplateJavaExtension.java:59)
    at org.openrewrite.java.tree.J$Lambda.acceptJava(J.java:2974)
    at org.openrewrite.java.tree.J.accept(J.java:64)
    at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
    ... 158 more
```

**Comment by kunli2** [comment]
Thanks Knut for fixing this!
