### ISSUE TITLE
IndexOutOfBoundsException in MethodParamPad with compact java record constructor

### ISSUE THREAD

**Issue by fprochazka** [openrewrite/rewrite#2964]
Hi, I've tried enabling some rules on our projects, and the `org.openrewrite.java.cleanup.MethodParamPad` failed on a compact record constructor.

```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at org.openrewrite.java.cleanup.MethodParamPad$MethodParamPadVisitor.visitMethodDeclaration(MethodParamPad.java:74)
	at org.openrewrite.java.cleanup.MethodParamPad$MethodParamPadVisitor.visitMethodDeclaration(MethodParamPad.java:46)
	at org.openrewrite.java.tree.J$MethodDeclaration.acceptJava(J.java:3442)
	at org.openrewrite.java.tree.J.accept(J.java:64)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:356)
	at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1268)
	at org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
	at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:145)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:126)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:145)
	at org.openrewrite.java.JavaVisitor.visitBlock(JavaVisitor.java:366)
	at org.openrewrite.java.JavaIsoVisitor.visitBlock(JavaIsoVisitor.java:94)
	at org.openrewrite.java.JavaIsoVisitor.visitBlock(JavaIsoVisitor.java:31)
```

I'm using them like this 

```java
public record HttpClientTrafficLogData(
    Request request,
    Response response
)
{

    public HttpClientTrafficLogData
    {
        Objects.requireNonNull(request, "request must not be null");
        Objects.requireNonNull(response, "response must not be null");
    }

}
```

**Comment by knutwannheden** [comment]
Thanks for the report @fprochazka ! Compact constructors were indeed an oversight in this recipe. This has now been fixed and will be available in the next release (and the current 7.38.0-SNAPSHOT builds).
