### ISSUE TITLE
`IllegalArgumentException` thrown by `JavaTemplate`

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite#2970]
When using `JavaTemplate` to replace a nested method invocation inside a ternary expression, an `IllegalArgumentException` may end up getting thrown (see below).

An example of this is the following Java class, where the static `String#format(String, Object...)` call is replaced by a corresponding `String#formatted(Object...)` instance method:

```java
                class A {
                    String foo(String s) { return s; }
                    void bar(Object o) {
                        String s = (o instanceof String s2) ?
                            foo(String.format("%s", "sam")) :
                            "";
                    }
                }
```

Stacktrace:

```
Caused by: java.lang.IllegalArgumentException: Expected a template that would generate exactly one statement to replace one statement, but generated 2. Template:
__P__.<java.lang.String>/*__p0__*/p().formatted(__P__.<String>/*__p1__*/p())
	at org.openrewrite.java.internal.template.JavaTemplateJavaExtension$1.maybeReplaceStatement(JavaTemplateJavaExtension.java:462)
	at org.openrewrite.java.internal.template.JavaTemplateJavaExtension$1.visitMethodInvocation(JavaTemplateJavaExtension.java:428)
	at org.openrewrite.java.internal.template.JavaTemplateJavaExtension$1.visitMethodInvocation(JavaTemplateJavaExtension.java:59)
	at org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3700)
	at org.openrewrite.java.tree.J.accept(J.java:64)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
	... 166 more
```

**Comment by knutwannheden** [comment]
@kunli2 The problem wasn't directly related to the `instanceof` pattern matching. It had to do with the logic in `BlockStatementTemplateGenerator#listTemplatedTrees()` which extracts the templated expressions. I think it may also have been possible to reproduce this without an `instanceof` expression.

I also identified an area where the stub generation for `J.Ternary` could be simplified, so I also integrated that into the fix.
