### ISSUE TITLE
List of Markers is immutable after parsing with JavaParser

### ISSUE THREAD

**Issue by fabapp2** [openrewrite/rewrite#3168]
The collection returned by `compilationUnit.getMarkers().getMarkers()` returns an unmodifiable list (Collections.enptyList()) in `7.40.2` which prevents adding new `Marker`s to the returned collection.
This test

````java
/**
 * @author Fabian Krüger
 */
public class JavaParserTest {

    @Test
    @ExpectedToFail
    void parsedCompilationUnitsShouldHaveModifiableListOfMarkers() {
        JavaParser.fromJavaVersion().build()
           .parse("class Pizza {}").get(0).getMarkers().getMarkers()
           .add(new SearchResult(UUID.randomUUID(), "test"));
    }

}
````

throws

````
java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractList.add(AbstractList.java:153)
	at java.base/java.util.AbstractList.add(AbstractList.java:111)
	at org.openrewrite.java.JavaParserTest.parsedCompilationUnitsShouldHaveMOdifiableListOfMarkers(JavaParserTest.java:32)
````

**Comment by fabapp2** [comment]
I solved it by using 

```java
cu.getMarkers().add(,,,)
```

in a loop. Would have preferred the mutable list though ;)

**Comment by knutwannheden** [comment]
Right. I think the List returned by `getMarkers()` should not be mutable in the first place. Or if it is, it should be a mutable copy. I think in the case of the `Markers.EMPTY` instance this is the case. I think we should in the scope of this issue make sure we return an unmodifiable view of the list.

**Comment by fabapp2** [comment]
Maybe providing a `getMarkers().addAll()` would be nice, freeing clients from doing the loop?
I would find a mutable copy very confusing tbh. Thinking,... why is access to the list required at all? Hiding the List implementation behind a custom method would make the API easier to use (but maybe I miss something).

However, feel free to close the issue then.

**Comment by timtebeek** [comment]
Fixed by commit c1443c0401 (July 2025) which reverted the problematic use of `Stream.toList()` (which returns immutable lists) back to mutable ArrayList collections. The `Markers.build()` method now ensures mutability, and operations like `addIfAbsent()`, `add()`, `compute()`, and `removeByType()` work correctly after parsing.
