### ISSUE TITLE
`NoClassDefFoundError: org/eclipse/jgit/lib/FileMode` on failing test run in IntelliJ

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite#3243]
After #3207 we now see errors when running a failing test from IntelliJ, when not run through Gradle.

```
java.lang.NoClassDefFoundError: org/eclipse/jgit/lib/FileMode
    at org.openrewrite.Result.computeDiff(Result.java:209)
    at org.openrewrite.Result.diff(Result.java:181)
    at org.openrewrite.Result.diff(Result.java:174)
    at org.openrewrite.Result.diff(Result.java:170)
    at org.openrewrite.Result.diff(Result.java:162)
    at org.openrewrite.test.RewriteTest.lambda$rewriteRun$9(RewriteTest.java:431)
    at org.assertj.core.description.LazyTextDescription.value(LazyTextDescription.java:33)
    at org.assertj.core.error.DescriptionFormatter.format(DescriptionFormatter.java:48)
    at org.assertj.core.error.MessageFormatter.format(MessageFormatter.java:62)
    at org.assertj.core.error.ShouldBeEqual.smartErrorMessage(ShouldBeEqual.java:169)
    at org.assertj.core.error.ShouldBeEqual.newAssertionError(ShouldBeEqual.java:117)
    at org.assertj.core.internal.Failures.failure(Failures.java:105)
    at org.assertj.core.internal.Objects.assertEqual(Objects.java:339)
    at org.assertj.core.api.AbstractAssert.isEqualTo(AbstractAssert.java:364)
    at org.assertj.core.api.AbstractStringAssert.isEqualTo(AbstractStringAssert.java:403)
    at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:436)
    at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:131)
    at org.openrewrite.gradle.UpdateJavaCompatibilityTest.handlesJavaExtension(UpdateJavaCompatibilityTest.java:126)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
    ... [truncated] 
Caused by: java.lang.ClassNotFoundException: org.eclipse.jgit.lib.FileMode
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    ... 88 more
```

Possibly related to the relocate we do of JGit: https://github.com/openrewrite/rewrite/blob/35acf34a85e9f35037328fb7ddb2759c229060ee/rewrite-core/build.gradle.kts#L34-L38

**Comment by timtebeek** [comment]
Looks related to this: https://youtrack.jetbrains.com/issue/IDEA-163411/Gradle-integration-is-broken-when-using-the-Shadow-Plugin

**Comment by timtebeek** [comment]
Based on [this comment](https://youtrack.jetbrains.com/issue/IDEA-163411/Gradle-integration-is-broken-when-using-the-Shadow-Plugin#focus=Comments-27-5774998.0-0) I tried adding this section into `rewrite-core/build.gradle.kts`:
```kotlin
// https://github.com/openrewrite/rewrite/issues/3243
tasks.register("unpackShadow", Copy::class) {
    dependsOn(shadowJar)
    println("Unpacking ${shadowJar.get().archiveFileName.get()} into $buildDir/unpacked-shadow")
    from(zipTree("$buildDir/libs/${shadowJar.get().archiveFileName.get()}"))
    into("$buildDir/unpacked-shadow")
}
tasks.named("build").configure {
    finalizedBy("unpackShadow")
}
```
So far no luck; possibly because of my unfamiliarity with Gradle; any help appreciated.

**Comment by timtebeek** [comment]
I suspect this block also suffers from the same, but is rare to encounter in the IDE.
https://github.com/openrewrite/rewrite/blob/35acf34a85e9f35037328fb7ddb2759c229060ee/rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java#L439-L440
