### ISSUE TITLE
`UpgradeDependencyVersionTest > upgradeAllDependenciesToPatchReleases()` relies upon live data, making tests inconsistent

### ISSUE THREAD

**Issue by JLLeitschuh** [openrewrite/rewrite#3325]
## What is the smallest, simplest way to reproduce the problem?
Run `./gradlew check` on the commit 2ae6ea0af2f8d20bec92577fb379c25a10b850f7

## What is the full stack trace of any errors you encountered?

```
> Task :rewrite-maven:test

UpgradeDependencyVersionTest > upgradeAllDependenciesToPatchReleases() FAILED
    org.opentest4j.AssertionFailedError: [Unexpected result in "pom.xml"
    diff --git a/pom.xml b/pom.xml
    index 9bdd71d..b82696f 100644
    --- a/pom.xml
    +++ b/pom.xml
    @@ -4,7 +4,7 @@ 
         <version>1</version>
         <properties>
             <guava.version>28.0-jre</guava.version>
    -        <spring.version>5.3.27</spring.version>
    +        <spring.version>5.3.28</spring.version>
             <spring.artifact-id>spring-jdbc</spring.artifact-id>
         </properties>
         <dependencies>
    ] 
    expected: 
      "<project>
          <groupId>org.openrewrite.example</groupId>
          <artifactId>my-app-server</artifactId>
          <version>1</version>
          <properties>
              <guava.version>28.0-jre</guava.version>
              <spring.version>5.3.27</spring.version>
              <spring.artifact-id>spring-jdbc</spring.artifact-id>
          </properties>
          <dependencies>
              <dependency>
                  <groupId>com.google.guava</groupId>
                  <artifactId>guava</artifactId>
                  <version>${guava.version}</version>
              </dependency>
              <dependency>
                  <groupId>org.springframework</groupId>
                  <artifactId>${spring.artifact-id}</artifactId>
                  <version>${spring.version}</version>
              </dependency>
              <dependency>
                  <groupId>com.fasterxml.jackson.core</groupId>
                  <artifactId>jackson-core</artifactId>
                  <version>2.13.5</version>
              </dependency>
          </dependencies>
      </project>"
     but was: 
      "<project>
          <groupId>org.openrewrite.example</groupId>
          <artifactId>my-app-server</artifactId>
          <version>1</version>
          <properties>
              <guava.version>28.0-jre</guava.version>
              <spring.version>5.3.28</spring.version>
              <spring.artifact-id>spring-jdbc</spring.artifact-id>
          </properties>
          <dependencies>
              <dependency>
                  <groupId>com.google.guava</groupId>
                  <artifactId>guava</artifactId>
                  <version>${guava.version}</version>
              </dependency>
              <dependency>
                  <groupId>org.springframework</groupId>
                  <artifactId>${spring.artifact-id}</artifactId>
                  <version>${spring.version}</version>
              </dependency>
              <dependency>
                  <groupId>com.fasterxml.jackson.core</groupId>
                  <artifactId>jackson-core</artifactId>
                  <version>2.13.5</version>
              </dependency>
          </dependencies>
      </project>"
        at java.base@17.0.1/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base@17.0.1/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base@17.0.1/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base@17.0.1/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:442)
        at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:129)
        at app//org.openrewrite.maven.UpgradeDependencyVersionTest.upgradeAllDependenciesToPatchReleases(UpgradeDependencyVersionTest.java:795)

> Task :rewrite-gradle:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :rewrite-maven:test

```

## Are you interested in [contributing a fix to OpenRewrite]

I can fix this specific instance of this problem, but the general problem is using live data that you can't control in your CI pipeline. Instead, it would be better to use a mock artifact server to test against. I don't have time to fix that whole problem, no.

**Comment by timtebeek** [comment]
Likely fix in https://github.com/openrewrite/rewrite/pull/3328 where we switch to a different way of checking the output, rather than bumping the version number.
