### ISSUE TITLE
`LazyValidated` produces ClassCastException when it is invalid

### ISSUE THREAD

**Issue by shanman190** [openrewrite/rewrite#3390]
## What version of OpenRewrite are you using?
OpenRewrite 8.1.5
OpenRewrite 8.2.0-SNAPSHOT

## How are you running OpenRewrite?

RewriteTest

## What is the smallest, simplest way to reproduce the problem?
```
package org.openrewrite;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class ValidatedTest {
    @Test
    void lazyInvalid() {
        Validated<?> validated = Validated.lazy("", () -> {
            throw new RuntimeException("Boom");
        });

        assertThat(validated.isInvalid()).isTrue();
        assertThat(validated.failures()).hasSize(1);
    }
}
```

## What did you expect to see?
Passing test case

## What did you see instead?
```
java.lang.ClassCastException: class org.openrewrite.Validated$LazyValidated cannot be cast to class org.openrewrite.Validated$Invalid (org.openrewrite.Validated$LazyValidated and org.openrewrite.Validated$Invalid are in unnamed module of loader 'app')

	at org.openrewrite.Validated.failures(Validated.java:59)
	at org.openrewrite.ValidatedTest.lazyInvalid(ValidatedTest.java:15)
```

**Comment by shanman190** [comment]
Slack thread: https://rewriteoss.slack.com/archives/C01A843MWG5/p1688163201125379

**Comment by shanman190** [comment]
Duplicate of #3385
