### ISSUE TITLE
Maven tests failed because it uses the wrong repo

### ISSUE THREAD

**Issue by jdelobel** [openrewrite/rewrite#3400]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite BOM v2.0.5

FYI, I work with my vpn company. My company has a private nexus. Why the `MavenPomDownloader` dont take my maven nexus company repo instead of `https://repo.maven.apache.org/maven2` ?

## What is the smallest, simplest way to reproduce the problem?

Tests failed.

## What is the full stack trace of any errors you encountered?

Here is the stacktrace:
```
java.lang.AssertionError: Failed to parse sources or run recipe

	at org.openrewrite.test.RewriteTest.lambda$defaultExecutionContext$10(RewriteTest.java:539)
	at org.openrewrite.maven.MavenParser.parseInputs(MavenParser.java:111)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:255)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:130)
	at com.myorg.RemoveDependencyTest.updateModelWhenAllDependenciesRemoved(RemoveDependencyTest.java:231)
Caused by: org.openrewrite.maven.MavenDownloadingExceptions
	at org.openrewrite.maven.MavenDownloadingExceptions.append(MavenDownloadingExceptions.java:44)
	at org.openrewrite.maven.tree.MavenResolutionResult.resolveDependencies(MavenResolutionResult.java:179)
	at org.openrewrite.maven.MavenParser.parseInputs(MavenParser.java:107)
	... 3 more
	Suppressed: org.openrewrite.maven.MavenDownloadingException: Unable to download POM. Tried repositories:
https://repo.maven.apache.org/maven2: java.net.SocketException: Connection reset
		at org.openrewrite.maven.internal.MavenPomDownloader.download(MavenPomDownloader.java:572)
		at org.openrewrite.maven.tree.ResolvedPom.resolveDependencies(ResolvedPom.java:598)
		at org.openrewrite.maven.tree.ResolvedPom.resolveDependencies(ResolvedPom.java:521)
		at org.openrewrite.maven.tree.MavenResolutionResult.resolveDependencies(MavenResolutionResult.java:174)
		... 4 more
```

**Comment by knutwannheden** [comment]
Just to clarify:
- The problem happens when you run a `RewriteTest` based JUnit test?
- Does the recipe work correctly when executed via Maven plugin?
- Do you have your company's private Nexus server listed in your `~/.m2/settings.xml` as the default repo?

**Comment by jdelobel** [comment]
> * /.m2/settings.xml



> Just to clarify:
> 
>     * The problem happens when you run a `RewriteTest` based JUnit test? Yes
> 
>     * Does the recipe work correctly when executed via Maven plugin?  deps are correctly resolved, in both cases: few seconds at works but 15 minutes in VPN 
> 
>     * Do you have your company's private Nexus server listed in your `~/.m2/settings.xml` as the default repo? Yes. There is no reference to `https://repo.maven.apache.org/maven2`. Just my company's private Nexus server is listed

**Comment by timtebeek** [comment]
If this is only/mostly a problem with running tests, then you might want to have a look at this [recent question and answer](https://stackoverflow.com/questions/76582382/openrewrite-enabling-local-maven-repository-during-junit-testing-of-a-recipe/76582495#76582495). We allow you to provide an ExecutionContext such that you have more control over the repositories used in your tests, which sounds like it could be useful here.

https://github.com/openrewrite/rewrite/blob/ad60832bb60e6da996f395d4abb09eb43f298822/rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeParentVersionTest.java#L66-L72

**Comment by timtebeek** [comment]
Hi @jdelobel ; did the above help you resolve your issue? I'm wondering if there's anything left to be done here.

**Comment by timtebeek** [comment]
I'm tentatively going to close this issue; let us know if there's anything you'd like to revisit!
