### ISSUE TITLE
[Bug] Cannot browse the marketplace because "0 recipes to search and transform code across NaN projects" 

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#3509]
![image](https://github.com/openrewrite/rewrite/assets/8935151/e344d165-c73a-491a-89b3-b7752dc03a9b)

Logs that might help : 

```javascript 
_app-c9d4fa7d6a441b69.js:211 Object undefined
ea @ _app-c9d4fa7d6a441b69.js:211
_app-c9d4fa7d6a441b69.js:211 TypeError: Cannot read properties of undefined (reading 'length')
    at _app-c9d4fa7d6a441b69.js:238:74935
    at eu (_app-c9d4fa7d6a441b69.js:238:70064)
    at _app-c9d4fa7d6a441b69.js:238:92276
    at tF (_app-c9d4fa7d6a441b69.js:238:61085)
    at new tj (_app-c9d4fa7d6a441b69.js:238:60537)
    at rY._promise (_app-c9d4fa7d6a441b69.js:238:92252)
    at rC._trans (_app-c9d4fa7d6a441b69.js:238:70143)
    at rC.bulkPut (_app-c9d4fa7d6a441b69.js:238:74640)
    at rY.<anonymous> (_app-c9d4fa7d6a441b69.js:211:235509) undefined
ea @ _app-c9d4fa7d6a441b69.js:211
_app-c9d4fa7d6a441b69.js:211 TypeError: Cannot read properties of undefined (reading 'length')
    at _app-c9d4fa7d6a441b69.js:238:74935
    at eu (_app-c9d4fa7d6a441b69.js:238:70064)
    at _app-c9d4fa7d6a441b69.js:238:92276
    at tF (_app-c9d4fa7d6a441b69.js:238:61085)
    at new tj (_app-c9d4fa7d6a441b69.js:238:60537)
    at rY._promise (_app-c9d4fa7d6a441b69.js:238:92252)
    at rC._trans (_app-c9d4fa7d6a441b69.js:238:70143)
    at rC.bulkPut (_app-c9d4fa7d6a441b69.js:238:74640)
    at rY.<anonymous> (_app-c9d4fa7d6a441b69.js:211:235509) undefined
ea @ _app-c9d4fa7d6a441b69.js:211
_app-c9d4fa7d6a441b69.js:211 Object undefined
ea @ _app-c9d4fa7d6a441b69.js:211
_app-c9d4fa7d6a441b69.js:211 TypeError: Cannot read properties of undefined (reading 'length')
    at _app-c9d4fa7d6a441b69.js:238:74935
    at eu (_app-c9d4fa7d6a441b69.js:238:70064)
    at _app-c9d4fa7d6a441b69.js:238:92276
    at tF (_app-c9d4fa7d6a441b69.js:238:61085)
    at new tj (_app-c9d4fa7d6a441b69.js:238:60537)
    at rY._promise (_app-c9d4fa7d6a441b69.js:238:92252)
    at rC._trans (_app-c9d4fa7d6a441b69.js:238:70143)
    at rC.bulkPut (_app-c9d4fa7d6a441b69.js:238:74640)
    at rY.<anonymous> (_app-c9d4fa7d6a441b69.js:211:235509) undefined
ea @ _app-c9d4fa7d6a441b69.js:211
_app-c9d4fa7d6a441b69.js:211 Object undefined
ea @ _app-c9d4fa7d6a441b69.js:211
_app-c9d4fa7d6a441b69.js:211 Object undefined
ea @ _app-c9d4fa7d6a441b69.js:211
_app-c9d4fa7d6a441b69.js:211 Object undefined
ea @ _app-c9d4fa7d6a441b69.js:211
_app-c9d4fa7d6a441b69.js:211 TypeError: Cannot read properties of undefined (reading 'length')
    at _app-c9d4fa7d6a441b69.js:238:74935
    at eu (_app-c9d4fa7d6a441b69.js:238:70064)
    at _app-c9d4fa7d6a441b69.js:238:92276
    at tF (_app-c9d4fa7d6a441b69.js:238:61085)
    at new tj (_app-c9d4fa7d6a441b69.js:238:60537)
    at rY._promise (_app-c9d4fa7d6a441b69.js:238:92252)
    at rC._trans (_app-c9d4fa7d6a441b69.js:238:70143)
    at rC.bulkPut (_app-c9d4fa7d6a441b69.js:238:74640)
    at rY.<anonymous> (_app-c9d4fa7d6a441b69.js:211:235509) undefined
ea @ _app-c9d4fa7d6a441b69.js:211
_app-c9d4fa7d6a441b69.js:211 Object undefined
ea @ _app-c9d4fa7d6a441b69.js:211
_app-c9d4fa7d6a441b69.js:211 Object undefined
ea @ _app-c9d4fa7d6a441b69.js:211
_app-c9d4fa7d6a441b69.js:211 Object undefined
ea @ _app-c9d4fa7d6a441b69.js:211
_app-c9d4fa7d6a441b69.js:211 Object undefined
ea @ _app-c9d4fa7d6a441b69.js:211
_app-c9d4fa7d6a441b69.js:211 TypeError: Cannot read properties of undefined (reading 'length')
    at _app-c9d4fa7d6a441b69.js:238:74935
    at eu (_app-c9d4fa7d6a441b69.js:238:70064)
    at _app-c9d4fa7d6a441b69.js:238:92276
    at tF (_app-c9d4fa7d6a441b69.js:238:61085)
    at new tj (_app-c9d4fa7d6a441b69.js:238:60537)
    at rY._promise (_app-c9d4fa7d6a441b69.js:238:92252)
    at rC._trans (_app-c9d4fa7d6a441b69.js:238:70143)
    at rC.bulkPut (_app-c9d4fa7d6a441b69.js:238:74640)
    at rY.<anonymous> (_app-c9d4fa7d6a441b69.js:211:235509) undefined
ea @ _app-c9d4fa7d6a441b69.js:211
_app-c9d4fa7d6a441b69.js:211 Object undefined
ea @ _app-c9d4fa7d6a441b69.js:211
```

```javascript

bulkPut(er, eo, ei) {
                let ea = Array.isArray(eo) ? eo : void 0
                  , es = (ei = ei || (ea ? void 0 : eo)) ? ei.allKeys : void 0;
                return this._trans("readwrite", eo=>{
                    let {auto: ei, keyPath: eu} = this.schema.primKey;
                    if (eu && ea)
                        throw new e5.InvalidArgument("bulkPut(): keys argument invalid on tables with inbound keys");
                    if (ea && ea.length !== er.length)
                        throw new e5.InvalidArgument("Arguments objects and keys must have the same length");
                    let ec = er.length
                      , ed = eu && ei ? er.map(rk(eu)) : er;
                    return this.core.mutate({
                        trans: eo,
                        type: "put",
                        keys: ea,
                        values: ed,
                        wantResults: es
                    }).then(({numFailures: er, results: eo, lastResult: ei, failures: ea})=>{
                        if (0 === er)
                            return es ? eo : ei;
                        throw new e2(`${this.name}.bulkPut(): ${er} of ${ec} operations failed`,ea)
                    }
                    )
                }
                )

```

**Comment by yeikel** [comment]
I meant to publish this in the board for the public service, my bad

**Comment by knutwannheden** [comment]
@yeikel This was probably just an intermittent failure while the service was being deployed. Please reopen if it is persistent on your end.

**Comment by knutwannheden** [comment]
@sjungling Do you maybe see anything we could / should do about this?

**Comment by yeikel** [comment]
Btw, I am still seeing it today. Are you still deploying? 

![image](https://github.com/openrewrite/rewrite/assets/8935151/f6eb1301-ad8f-4017-83ee-f3e3f4b4d0ce)

**Comment by yeikel** [comment]
Fun fact, navigating to build and back to marketplace magically fixed it

**Comment by knutwannheden** [comment]
> Btw, I am still seeing it today. Are you still deploying?

No, but maybe "again" :-)

If you keep seeing this, we will have to investigate. Thanks for the update!
