### ISSUE TITLE
NPE in GitProvenance

### ISSUE THREAD

**Issue by Bananeweizen** [openrewrite/rewrite#3593]
This one is not from USING OpenRewrite, but from building the maven plugin 5.8.0-SNAPSHOT from current head. One of the tests triggers an NPE in core code.

## What is the smallest, simplest way to reproduce the problem?

```
cd rewrite-maven-plugin
mvn verify
```
## What is the full stack trace of any errors you encountered?

```
[INFO] Running org.openrewrite.maven.MavenMojoProjectParserTest
[debug] Unable to determine git provenance

java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.toFile()" because "projectDir" is null
        at org.openrewrite.marker.GitProvenance.fromGitConfig(GitProvenance.java:187)
        at org.openrewrite.marker.GitProvenance.fromProjectDirectory(GitProvenance.java:175)
        at org.openrewrite.maven.MavenMojoProjectParser.gitProvenance(MavenMojoProjectParser.java:647)
        at org.openrewrite.maven.MavenMojoProjectParser.generateProvenance(MavenMojoProjectParser.java:263)
        at org.openrewrite.maven.MavenMojoProjectParserTest.givenNoJavaVersionInformationExistsInMavenThenJavaSpecificationVersionShouldBeUsed(MavenMojoProjectParserTest.java:29)
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Not this one. I'm not sure what would be reasonable here for the null case.

**Comment by timtebeek** [comment]
Thanks for pointing this one out! Fixed now.
