### ISSUE TITLE
Problem with inner Class named '$' in JavaTemplate

### ISSUE THREAD

**Issue by MBoegers** [openrewrite/rewrite#3623]
## What version of OpenRewrite are you using?
I am using current main (Commit: d53b36febdc9ba609ae64295bcaa54b9fe4169b8)
rewrite-java 8.5.0-SNAPSHOT

## How are you running OpenRewrite?
Initially via tests in PR https://github.com/openrewrite/rewrite-migrate-java/pull/285
Reproduced with test in rewrite-java directly.

## What is the smallest, simplest way to reproduce the problem?
Reference an inner class with name `$` inside a JavaTemplate 

## What did you expect to see?
JavaTemplate has to deal with `$` as name of inner classes.
They resutl into `A$$`as FQN when defined as `A.$`.

## What did you see instead?
`__P__.<error>`

## What is the full stack trace of any errors you encountered?
_none_

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?
Yes, as it blocks my PR :D

**Comment by MBoegers** [comment]
see https://github.com/openrewrite/rewrite/compare/main...MBoegers:rewrite:3623-%24-as-inner-class#diff-4c3061e863c60e5a5391eb3c2b843b66b4113096c6527d0c09029d3338484b9e for reproducer

**Comment by timtebeek** [comment]
Nice find! sorry this didn't get a lot of traction before; it's hard to get to everything! What do you want to do now? Do you need input on anything?

**Comment by MBoegers** [comment]
First of all, thanks an no worries. Its rarely used and I mentioned working on it ;).
I just documented my find as I try to understand the purpose of $ in OpenRewrite. It seems like $ is wider used in OpenRewrite than specified the JLS and that leads to sime wierd edge cases.
Would it be a hight value target to comply OpenRewrites usage of $ with the JLS?

**Comment by MBoegers** [comment]
I think I made some progress. 
- TypeUtils.toFullyQualifiedName seem to handle $ better (see [TypeUtilsTest L 150 following](https://github.com/openrewrite/rewrite/compare/main...MBoegers:rewrite:3623-$-as-inner-class#diff-11e9181d7f5fc01636de0bf3331ddc98f39c3eef14fd0d63020757d95bf6f638R250-R288))
- All occurrences of String.replace("$", ".") in rewrite-java* now use TypeUtils.toFullyQualifiedName (namely Substitutions and RemoveUnusedImports) with green tests

I have a strange behavior in [JavaTemplateSubstitutionTest.anyForInnerClass](https://github.com/openrewrite/rewrite/compare/main...MBoegers:rewrite:3623-$-as-inner-class#diff-f622898fc7eeda53c6f825ba747fa09920092f41b8a7f0ba81a7f9e475a15b5dR88).
If I run the test I get
```log
class A {
   void foo() {
-      $ test = new $();
+      $ test = new A.$();
     }
 //...
}
```
If I change [Line 125](https://github.com/openrewrite/rewrite/compare/main...MBoegers:rewrite:3623-$-as-inner-class#diff-f622898fc7eeda53c6f825ba747fa09920092f41b8a7f0ba81a7f9e475a15b5dR125) to `new A.$()` which also should be correct, I get 
```log
java.lang.IllegalStateException: AST contains missing or invalid type information
NewClass->NamedVariable->VariableDeclarations->Block->MethodDeclaration->Block->ClassDeclaration->CompilationUnit
/*~~(NewClass type is missing or malformed)~~>*/new A.$()
	at org.openrewrite.java.Assertions.assertValidTypes(Assertions.java:92)
	at org.openrewrite.java.Assertions.validateTypes(Assertions.java:62)
	at org.openrewrite.java.Assertions$$Lambda$440/0x00000008001ecfa8.accept(Unknown Source)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:466)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:132)
	at org.openrewrite.java.JavaTemplateSubstitutionsTest.anyForInnerClass(JavaTemplateSubstitutionsTest.java:89)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```
That makes me feel like I miss a thing here. Any suggestions?
