### ISSUE TITLE
Parsing pom throws error 'java.util.regex.PatternSyntaxException: Illegal repetition near index 0 ${pom.groupId}' 

### ISSUE THREAD

**Issue by fabapp2** [openrewrite/rewrite#367]
When parsing the pom from Spring Petclinic example the paresing of the pom.xml fails.
The application builds and runs succesfully but OR throws this exception when parsing the pom.xml:

```
java.util.regex.PatternSyntaxException: Illegal repetition near index 0
${pom.groupId}
^

	at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
	at java.base/java.util.regex.Pattern.closure(Pattern.java:3320)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2213)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2068)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1782)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1428)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1068)
	at java.base/java.util.regex.Pattern.matches(Pattern.java:1173)
	at java.base/java.lang.String.matches(String.java:2024)
	at org.openrewrite.maven.internal.RawMavenResolver.lambda$processDependencies$4(RawMavenResolver.java:212)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.openrewrite.maven.internal.RawMavenResolver.processDependencies(RawMavenResolver.java:322)
	at org.openrewrite.maven.internal.RawMavenResolver.processTask(RawMavenResolver.java:125)
	at org.openrewrite.maven.internal.RawMavenResolver.resolve(RawMavenResolver.java:106)
	at org.openrewrite.maven.internal.RawMavenResolver.resolve(RawMavenResolver.java:82)
	at org.openrewrite.maven.MavenParser.lambda$parseInputs$1(MavenParser.java:74)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.openrewrite.maven.MavenParser.parseInputs(MavenParser.java:77)
	at org.openrewrite.Parser.parse(Parser.java:38)
       ...
```

**parsed pom.xml**

https://github.com/spring-petclinic/spring-framework-petclinic/blob/master/pom.xml

**Comment by fabapp2** [comment]
HI @sambsnyd, with version 7.1.0 the parsing works fine.
