### ISSUE TITLE
🐛 e.replaceAll is not a function

### ISSUE THREAD

**Issue by undament** [openrewrite/rewrite#3709]
```
TypeError: e.replaceAll is not a function
    at getMarkerColumnsFromLine (https://app.moderne.io/_next/static/chunks/pages/results/%5BrecipeRunId%5D/details/%5Brepo%5D-52c01db7605142fe.js:1:18049)
    at https://app.moderne.io/_next/static/chunks/pages/results/%5BrecipeRunId%5D/details/%5Brepo%5D-52c01db7605142fe.js:1:18591
    at Array.map (<anonymous>)
    at Diff.findMarkerLocations (https://app.moderne.io/_next/static/chunks/pages/results/%5BrecipeRunId%5D/details/%5Brepo%5D-52c01db7605142fe.js:1:18584)
    at https://app.moderne.io/_next/static/chunks/pages/results/%5BrecipeRunId%5D/details/%5Brepo%5D-52c01db7605142fe.js:1:19875
    at Array.map (<anonymous>)
    at new Diff (https://app.moderne.io/_next/static/chunks/pages/results/%5BrecipeRunId%5D/details/%5Brepo%5D-52c01db7605142fe.js:1:19795)
    at FileDiffView (https://app.moderne.io/_next/static/chunks/pages/results/%5BrecipeRunId%5D/details/%5Brepo%5D-52c01db7605142fe.js:1:41681)
    at Xh (https://app.moderne.io/_next/static/chunks/framework-030511d01d8c6be9.js:9:63538)
    at _ (https://app.moderne.io/_next/static/chunks/framework-030511d01d8c6be9.js:9:120051)
```

https://app.moderne.io/results/ob3hv6piA/details/eyJfX3R5cGVuYW1lIjoiR2l0SHViUmVwb3NpdG9yeSIsIm9yaWdpbiI6ImdpdGh1Yi5jb20iLCJwYXRoIjoibW9kZXJuZWluYy9zcHJpbmctcGV0Y2xpbmljIiwiYnJhbmNoIjoiMi4wLjAifQ==?referrer=%2Fresults%2Fob3hv6piA

**Comment by timtebeek** [comment]
These results can no longer be found, and from the stacktrace I suspect it was a temporary issue in the web interface. Do let me know if you still have issues; I'll close this issue on the assumption that it has been resolved.
