### ISSUE TITLE
🐛 Cannot read properties of undefined (reading 'pageInfo')

### ISSUE THREAD

**Issue by JLLeitschuh** [openrewrite/rewrite#3722]
```
TypeError: Cannot read properties of undefined (reading 'pageInfo')
    at UserRecipeRuns (https://app.moderne.io/_next/static/chunks/pages/results/recent-c62c0f1000cd43f6.js:3:26705)
    at Xh (https://app.moderne.io/_next/static/chunks/framework-030511d01d8c6be9.js:9:63538)
    at dj (https://app.moderne.io/_next/static/chunks/framework-030511d01d8c6be9.js:9:75136)
    at _ (https://app.moderne.io/_next/static/chunks/framework-030511d01d8c6be9.js:9:120825)
    at Vk (https://app.moderne.io/_next/static/chunks/framework-030511d01d8c6be9.js:9:111524)
    at Uk (https://app.moderne.io/_next/static/chunks/framework-030511d01d8c6be9.js:9:111452)
    at Jk (https://app.moderne.io/_next/static/chunks/framework-030511d01d8c6be9.js:9:111315)
    at Ok (https://app.moderne.io/_next/static/chunks/framework-030511d01d8c6be9.js:9:107683)
    at Fk (https://app.moderne.io/_next/static/chunks/framework-030511d01d8c6be9.js:9:108489)
    at jg (https://app.moderne.io/_next/static/chunks/framework-030511d01d8c6be9.js:9:47429)
```

https://app.moderne.io/results/recent

**Comment by timtebeek** [comment]
Thanks for reporting here! We're exploring the issue.

**Comment by timtebeek** [comment]
This page is also up again; thanks for notifying us!
