### ISSUE TITLE
Fallthrough case statement in groovy causes paring error

### ISSUE THREAD

**Issue by reallyinsane** [openrewrite/rewrite#3759]
## What version of OpenRewrite are you using?
I am using

- OpenRewrite v8.8.0
- Maven/Gradle plugin v5.14.1
- rewrite-groovy_module_ v8.8.0

## How are you running OpenRewrite?
I'm trying to build my own recipes manipulating Jenkinsfile (groovy). Therefore I run tests and execute the recipe using the Maven plugin.

## What is the smallest, simplest way to reproduce the problem?

The simplest way is having a switch statement in a groovy file with a fallthrough case statement. The parser of openrewrite expects a blockstatement following the case statement, so it fails always.

You can use the test org.openrewrite.groovy.tree.SwitchTest#fallthroughCase in my fork.

```java
switch("foo") {
  case "foo":
  case "bar": {
    break
  }
}
```

## What did you expect to see?

I'd expect that a fallthrough statement is accepted.

## What did you see instead?
A parsing error.

```
Failed to parse file.groovy at cursor position 31. The next 10 characters in the original source are `
    case `
org.openrewrite.groovy.GroovyParsingException: Failed to parse file.groovy at cursor position 31. The next 10 characters in the original source are `
    case `
	at app//org.openrewrite.groovy.GroovyParserVisitor.visit(GroovyParserVisitor.java:174)
	at app//org.openrewrite.groovy.GroovyParser.lambda$parseInputs$4(GroovyParser.java:154)
	at app//org.openrewrite.groovy.GroovyParser$$Lambda$480/0x0000000800dace00.apply(Unknown Source)
	at java.base@17.0.2/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base@17.0.2/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base@17.0.2/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base@17.0.2/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base@17.0.2/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base@17.0.2/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base@17.0.2/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@17.0.2/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:272)
	at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:132)
	at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:127)
	at app//org.openrewrite.groovy.tree.SwitchTest.fallthroughCase(SwitchTest.java:145)
	at java.base@17.0.2/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base@17.0.2/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base@17.0.2/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ClassCastException: class org.codehaus.groovy.ast.stmt.EmptyStatement$1 cannot be cast to class org.codehaus.groovy.ast.stmt.BlockStatement (org.codehaus.groovy.ast.stmt.EmptyStatement$1 and org.codehaus.groovy.ast.stmt.BlockStatement are in unnamed module of loader 'app')
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.visitCaseStatement(GroovyParserVisitor.java:981)
	at org.codehaus.groovy.ast.stmt.CaseStatement.visit(CaseStatement.java:55)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.visit(GroovyParserVisitor.java:561)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.convert(GroovyParserVisitor.java:1967)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.convertAll(GroovyParserVisitor.java:1961)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.visitSwitch(GroovyParserVisitor.java:1741)
	at org.codehaus.groovy.ast.stmt.SwitchStatement.visit(SwitchStatement.java:53)
	at org.openrewrite.groovy.GroovyParserVisitor.convertTopLevelStatement(GroovyParserVisitor.java:2042)
	at org.openrewrite.groovy.GroovyParserVisitor.visit(GroovyParserVisitor.java:160)
	... 17 more
```

I already fixed it in my fork.

**Comment by timtebeek** [comment]
Thanks a lot for reporting and fixing the issue; you should be able to use [our snapshot versions](https://docs.openrewrite.org/reference/snapshot-instructions) to try out this change until the next release, usually within a week or two.
