### ISSUE TITLE
🐛 Cannot read properties of undefined (reading 'organization')

### ISSUE THREAD

**Issue by sbenzal** [openrewrite/rewrite#3825]
```
TypeError: Cannot read properties of undefined (reading 'organization')
    at Z (https://app.moderne.io/_next/static/chunks/pages/_app-239a58656a093b2e.js:206:123659)
    at https://app.moderne.io/_next/static/chunks/pages/_app-239a58656a093b2e.js:206:122945
    at Array.map (<anonymous>)
    at R (https://app.moderne.io/_next/static/chunks/pages/_app-239a58656a093b2e.js:206:122931)
    at G (https://app.moderne.io/_next/static/chunks/pages/_app-239a58656a093b2e.js:206:128678)
    at ak (https://app.moderne.io/_next/static/chunks/framework-314c182fa7e2bf37.js:9:60903)
    at up (https://app.moderne.io/_next/static/chunks/framework-314c182fa7e2bf37.js:9:72785)
    at i (https://app.moderne.io/_next/static/chunks/framework-314c182fa7e2bf37.js:9:120317)
    at oD (https://app.moderne.io/_next/static/chunks/framework-314c182fa7e2bf37.js:9:99073)
    at https://app.moderne.io/_next/static/chunks/framework-314c182fa7e2bf37.js:9:98940
```

https://app.moderne.io/marketplace

**Comment by timtebeek** [comment]
Hi @sbenzal thanks for reporting your issue here! When I load `https://app.moderne.io/marketplace` here in my browser I don't see the above issue. Did you already try if a hard refresh solves the issue for you? Or might it have been a temporary issue?

**Comment by sbenzal** [comment]
Hi @timtebeek , thanks for answering, the problem happens when I try to change the organization in app.moderne.io, since yesterday it does not work and when I click on it I get the following error message
![image](https://github.com/openrewrite/rewrite/assets/147181266/25a6f003-00dd-40ec-b8e1-4ff048bb374

I dont know if its possible to see it, but it says:
TypeError: Cannot read properties of undefined (reading 'organization')
    at Z (https://app.moderne.io/_next/static/chunks/pages/_app-239a58656a093b2e.js:206:123659)
    at https://app.moderne.io/_next/static/chunks/pages/_app-239a58656a093b2e.js:206:122945
    at Array.map (<anonymous>)
    at R (https://app.moderne.io/_next/static/chunks/pages/_app-239a58656a093b2e.js:206:122931)
    at G (https://app.moderne.io/_next/static/chunks/pages/_app-239a58656a093b2e.js:206:128678)
    at ak (https://app.moderne.io/_next/static/chunks/framework-314c182fa7e2bf37.js:9:60903)
    at up (https://app.moderne.io/_next/static/chunks/framework-314c182fa7e2bf37.js:9:72785)
    at i (https://app.moderne.io/_next/static/chunks/framework-314c182fa7e2bf37.js:9:120317)
    at oD (https://app.moderne.io/_next/static/chunks/framework-314c182fa7e2bf37.js:9:99073)
    at https://app.moderne.io/_next/static/chunks/framework-314c182fa7e2bf37.js:9:98940

**Comment by sbenzal** [comment]
I also tried in another browser and its not working either

**Comment by timtebeek** [comment]
Hmm tried that here as well, but not seeing any such issues; I'm hoping Scott has more insights once he comes online.

**Comment by natedanner** [comment]
@sbenzal We have deployed a fix for this issue. You may need to refresh your browser. Please try again.

**Comment by sbenzal** [comment]
Yes, now it works, thanks! 😊
