### ISSUE TITLE
🐛 Cannot read properties of undefined (reading 'options')

### ISSUE THREAD

**Issue by rahulpatil-dev** [openrewrite/rewrite#3927]
```
TypeError: Cannot read properties of undefined (reading 'options')
    at o (https://app.moderne.io/_next/static/chunks/9020-fac42c9f310a5a31.js:1:18211)
    at s (https://app.moderne.io/_next/static/chunks/9020-fac42c9f310a5a31.js:1:18429)
    at ak (https://app.moderne.io/_next/static/chunks/framework-314c182fa7e2bf37.js:9:60903)
    at up (https://app.moderne.io/_next/static/chunks/framework-314c182fa7e2bf37.js:9:72785)
    at i (https://app.moderne.io/_next/static/chunks/framework-314c182fa7e2bf37.js:9:120317)
    at oD (https://app.moderne.io/_next/static/chunks/framework-314c182fa7e2bf37.js:9:99073)
    at https://app.moderne.io/_next/static/chunks/framework-314c182fa7e2bf37.js:9:98940
    at oO (https://app.moderne.io/_next/static/chunks/framework-314c182fa7e2bf37.js:9:98947)
    at oE (https://app.moderne.io/_next/static/chunks/framework-314c182fa7e2bf37.js:9:95699)
    at oP (https://app.moderne.io/_next/static/chunks/framework-314c182fa7e2bf37.js:9:96088)
```

https://app.moderne.io/recipes/builder

**Comment by timtebeek** [comment]
hi @rahulpatil-dev ! I'm not immediately seeing the same; could you let us know what steps you went through to get this error? Did you add any specific recipe to the builder from another page for instance? Or did you previously add recipes to the builder and returned to the page now?
