### ISSUE TITLE
RemoveObjectsIsNull doesn't remove unnecessary parentheses, if it

### ISSUE THREAD

**Issue by Bananeweizen** [openrewrite/rewrite#4031]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v1.2.3
- Maven/Gradle plugin v1.2.3
- rewrite-_module_ v1.2.3

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a single module project.
```xml
<plugin>
  <groupId>org.openrewrite.maven</groupId>
  <artifactId>rewrite-maven-plugin</artifactId>
  <version>1.2.3</version>
  <configuration>
    ... 
  </configuration>
</plugin>
```

## What is the smallest, simplest way to reproduce the problem?

```java
class A {
    void foo(String bar) {
        int i = 5;
    }
}
```

## What did you expect to see?

```java
class A {
    void foo(String bar) {
        int i = 5;
    }
}
```

## What did you see instead?

```java
class A {
    void foo(String bar) {
        int i = 5;
    }
}
```

## What is the full stack trace of any errors you encountered?

```
stacktrace output here
```

**Comment by timtebeek** [comment]
Thanks for the report! Curious indeed. The difference between directly calling a visitor with an argument and `doAfterVisit` is that the first approach only applies to the argument, whereas `doAfterVisit` applies to the whole file. There might be cases where that ends up removing parentheses that are more of a personal preference, unrelated to the `RemoveObjectsIsNull` change. That's why the first case is preferred where possible.

Perhaps a good first step is a failing test using the above, and then we can try to see how we can debug and fix this case. I'm suspicious of the `getCursor()`passed into the `visitNonNull`, given that there's also a `replaced` argument. Elsewhere we update the cursor in such cases, but I'd have to dive in to this particular case to know if that's a fix here. Would appreciate the help!

**Comment by protocol7** [comment]
We're also seeing this with `org.openrewrite:rewrite-core:8.59.1`. Here's a test case:

```java
  @Test
  public void objectIsNullParenthesis() {
    rewriteRun(
        spec -> spec.recipe(new RemoveObjectsIsNull()),
        java(
            """
            package com.helloworld;
            
            import java.util.Objects;

            public class Foo {
              public boolean foo(Object o) {
                return Objects.isNull(o);
              }
            }
            """, """
            package com.helloworld;
            
            import java.util.Objects;

            public class Foo {
              public boolean foo(Object o) {
                return o == null;
              }
            }
            """));
  }
```

```
org.opentest4j.AssertionFailedError: [Unexpected result in "com/helloworld/Foo.java":
diff --git a/com/helloworld/Foo.java b/com/helloworld/Foo.java
index 84dd69b..04577a1 100644
--- a/com/helloworld/Foo.java
+++ b/com/helloworld/Foo.java
@@ -1,9 +1,7 @@
 package com.helloworld;

-import java.util.Objects;
-
 public class Foo {
   public boolean foo(Object o) {
-    return o == null;
+    return (o == null);
   }
 }
\ No newline at end of file
]
expected:
  "package com.helloworld;

  import java.util.Objects;

  public class Foo {
    public boolean foo(Object o) {
      return o == null;
    }
  }"
 but was:
  "package com.helloworld;

  public class Foo {
    public boolean foo(Object o) {
      return (o == null);
    }
  }"
	at org.openrewrite.test.RewriteTest.assertContentEquals(RewriteTest.java:622)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:511)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:130)
```

From a quick debug, it seems like the `SimplifyBooleanExpressionVisitor` is invoked, but doesn't clean up the parenthesis as expected.

**Comment by timtebeek** [comment]
Thanks both! The runnable test helped:
- https://github.com/openrewrite/rewrite/pull/5900
