### ISSUE TITLE
Java11Parser StringIndexOutOfBoundsExceptions

### ISSUE THREAD

**Issue by gadams00** [openrewrite/rewrite#404]
Encountered parsing spring-framework/spring-test.

```
17:19:33.985 [main] ERROR i.m.ingest.parse.GradleProjectParser - Error parsing
org.openrewrite.java.JavaParsingException: Failed to convert for the following cursor stack:--- BEGIN PATH ---
JCCompilationUnit(sourceFile = /Users/gadams/git/external/spring-framework/spring-test/src/test/java/org/springframework/test/web/servlet/samples/context/WebAppResourceTests.java)
JCClassDecl(name = WebAppResourceTests, line = 45)
--- END PATH ---

	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1367)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1373)
	at org.openrewrite.java.Java11ParserVisitor.convertStatements(Java11ParserVisitor.java:1471)
	at org.openrewrite.java.Java11ParserVisitor.visitClass(Java11ParserVisitor.java:432)
	at org.openrewrite.java.Java11ParserVisitor.visitClass(Java11ParserVisitor.java:61)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1344)
	at org.openrewrite.java.Java11ParserVisitor.convertAll(Java11ParserVisitor.java:1396)
	at org.openrewrite.java.Java11ParserVisitor.visitCompilationUnit(Java11ParserVisitor.java:463)
	at org.openrewrite.java.Java11ParserVisitor.visitCompilationUnit(Java11ParserVisitor.java:61)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
	at org.openrewrite.java.Java11Parser.lambda$parseInputs$1(Java11Parser.java:214)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.openrewrite.java.Java11Parser.parseInputs(Java11Parser.java:235)
	at org.openrewrite.Parser.parse(Parser.java:39)
	at io.moderne.ingest.parse.GradleProjectParser.parseEclipseProject(GradleProjectParser.java:83)
	at io.moderne.ingest.parse.GradleProjectParser.parseEclipseProject(GradleProjectParser.java:87)
	at io.moderne.ingest.parse.GradleProjectParser.parse(GradleProjectParser.java:58)
	at io.moderne.ingest.parse.GradleProjectParser.main(GradleProjectParser.java:145)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.AbstractStringBuilder.setLength(AbstractStringBuilder.java:275)
	at java.base/java.lang.StringBuilder.setLength(StringBuilder.java:85)
	at org.openrewrite.java.tree.Space.format(Space.java:172)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1344)
	... 27 common frames omitted
```

**Comment by traceyyoshima** [comment]
Attempted to reproduce this error, but couldn't surface a `java.lang.StringIndexOutOfBoundsException: String index out of range: -1`. It is likely already fixed via a change Pat W put in place for Space.
