### ISSUE TITLE
XPathMatcher does not support paths containing "//" and conditions

### ISSUE THREAD

**Issue by SilasSchaprian** [openrewrite/rewrite#4119]
I am using

- OpenRewrite v8.21.0
- Maven plugin v5.25.0
- rewrite-xml_ v8.21.0

## How are you running OpenRewrite?

I am using using the OpenRewrite Testing Framework to author a custom Recipe to change XML-tag values or the property used as value. The Custom Recipe is a fork of the ChangeXMLTagValue Recipe.
```xml
 <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.openrewrite.recipe</groupId>
        <artifactId>rewrite-recipe-bom</artifactId>
        <version>2.8.1</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <!-- rewrite-java dependencies only necessary for Java Recipe development -->
    <dependency>
      <groupId>org.openrewrite</groupId>
      <artifactId>rewrite-java</artifactId>
      <scope>compile</scope>
    </dependency>

    <!-- You only need the version that corresponds to your current
    Java version. It is fine to add all of them, though, as
    they can coexist on a classpath. -->
    <dependency>
      <groupId>org.openrewrite</groupId>
      <artifactId>rewrite-java-8</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.openrewrite</groupId>
      <artifactId>rewrite-java-11</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.openrewrite</groupId>
      <artifactId>rewrite-java-17</artifactId>
      <scope>runtime</scope>
    </dependency>

    <!-- rewrite-maven dependency only necessary for Maven Recipe development -->
    <dependency>
      <groupId>org.openrewrite</groupId>
      <artifactId>rewrite-maven</artifactId>
      <scope>compile</scope>
    </dependency>

    <!-- rewrite-yaml dependency only necessary for Yaml Recipe development -->
    <dependency>
      <groupId>org.openrewrite</groupId>
      <artifactId>rewrite-yaml</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.openrewrite</groupId>
      <artifactId>rewrite-json</artifactId>
      <scope>compile</scope>
    </dependency>

    <!-- rewrite-properties dependency only necessary for Properties Recipe development -->
    <dependency>
      <groupId>org.openrewrite</groupId>
      <artifactId>rewrite-properties</artifactId>
      <scope>compile</scope>
    </dependency>

    <!-- rewrite-xml dependency only necessary for XML Recipe development -->
    <dependency>
      <groupId>org.openrewrite</groupId>
      <artifactId>rewrite-xml</artifactId>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>org.openrewrite.recipe</groupId>
      <artifactId>rewrite-testing-frameworks</artifactId>
      <version>2.6.0</version>
    </dependency>

    <dependency>
      <groupId>org.openrewrite.recipe</groupId>
      <artifactId>rewrite-static-analysis</artifactId>
      <version>1.4.2</version>
    </dependency>

    <!-- For authoring tests for any kind of Recipe -->
    <dependency>
      <groupId>org.openrewrite</groupId>
      <artifactId>rewrite-test</artifactId>
      <scope>test</scope>
    </dependency>


    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.18.32</version>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>org.apache.maven</groupId>
      <artifactId>maven-model</artifactId>
      <version>3.9.6</version>
    </dependency>
  </dependencies>
```

## What is the smallest, simplest way to reproduce the problem?
```java
@Override
    public void defaults(RecipeSpec spec) {
        spec.recipe(
                new ChangeTagValue("//dependency[artifactId='your-artifactId']/version", null,
                        "20.9.5"));
    }

    @Test
    void errorCase_gitHubIssue() {
        rewriteRun(
                xml("""
                                <project>                                    
                                    <dependencyManagement>
                                        <dependencies>
                                          <dependency>
                                            <groupId>your.groupId</groupId>
                                            <artifactId>your-artifactId</artifactId>
                                            <version>randomValue</version>
                                            <type>pom</type>
                                            <scope>import</scope>
                                          </dependency>
                                        </dependencies>
                                      </dependencyManagement>
                                </project>
                                """,
                        """
                                 <project>
                                     <dependencyManagement>
                                         <dependencies>
                                           <dependency>
                                             <groupId>your.groupId</groupId>
                                             <artifactId>your-artifactId</artifactId>
                                             <version>20.9.5</version>
                                             <type>pom</type>
                                             <scope>import</scope>
                                           </dependency>
                                         </dependencies>
                                       </dependencyManagement>
                                 </project>
                                """)
        );
    }
```

## What did you expect to see?
I would expect the recipe to change the Tag-Value

## What did you see instead?
```
java.lang.AssertionError: Recipe was expected to make a change but made no changes.
```

## What is the full stack trace of any errors you encountered?

```
stacktrace output here
```
java.lang.AssertionError: Recipe was expected to make a change but made no changes.

	at org.openrewrite.test.LargeSourceSetCheckingExpectedCycles.afterCycle(LargeSourceSetCheckingExpectedCycles.java:118)
	at org.openrewrite.RecipeScheduler.runRecipeCycles(RecipeScheduler.java:97)
	at org.openrewrite.RecipeScheduler.scheduleRun(RecipeScheduler.java:41)
	at org.openrewrite.Recipe.run(Recipe.java:344)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:375)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:133)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:128)
	at de.gothaer.refactorings.openrewrite.recipes.util.ChangeXMLTagValueOrPropertyTest.errorCase_gitHubIssue(ChangeXMLTagValueOrPropertyTest.java:21)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

Process finished with exit code -1

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?
I would like to contributing a PR :)

**Comment by knutwannheden** [comment]
@SilasSchaprian Thanks for your offer to help with this! You can just [create a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo) and push your commits in a branch there and create a PR from that.

**Comment by SilasSchaprian** [comment]
The PR is ready for review :)
