### ISSUE TITLE
Groovy Enum is throwing "Failed to parse"  "UnsupportedOperationException: enum fields are not implemented."

### ISSUE THREAD

**Issue by gtiwari333** [openrewrite/rewrite#4252]
## What version of OpenRewrite are you using?
 
I am using https://github.com/gtiwari333/openrewrite-groovy-bug/blob/main/init.gradle

- org.openrewrite.recipe:rewrite-recipe-bom  - 2.1.20
- org.openrewrite:rewrite-gradle-plugin - latest.release
- groovy 4.0.21
- jdk 17/21
- gradle 8.8

 
 

## How are you running OpenRewrite?
 `%./gradlew  clean rewriteRun --init-script init.gradle --info`

 

## What is the smallest, simplest way to reproduce the problem?

Checkout the following project and run `./gradlew  clean rewriteRun --init-script init.gradle --info`

Im seeing similar behavior with both jdk17 and jdk21 

https://github.com/gtiwari333/openrewrite-groovy-bug/blob/main/README.md 

## What did you expect to see?
 No failures. AutoFormat recipe should run on the code.

## What did you see instead?
 ```Error during rewrite run
org.openrewrite.groovy.GroovyParsingException: Failed to parse src/main/groovy/com/example/demo/Status.groovy at cursor position 39. The next 10 characters in the original source are ` //enum al`
        at org.openrewrite.groovy.GroovyParserVisitor.visit(GroovyParserVisitor.java:175)
 ....
  Caused by: java.lang.UnsupportedOperationException: enum fields are not implemented.
        at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyClassVisitor.visitEnumField(GroovyParserVisitor.java:357)
        at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyClassVisitor.visitField(GroovyParserVisitor.java:348)
        at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyClassVisitor.lambda$visitClassBlock$3(GroovyParserVisitor.java:332)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
```

## What is the full stack trace of any errors you encountered?
 Run the `./gradlew  clean rewriteRun --init-script init.gradle --info` command to get full stacktrace. I've provided relevant bits above.

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Not too familiar how AST works. But i can try.

**Comment by timtebeek** [comment]
Thanks for the helpful sample application @gtiwari333 ! Looks like we're indeed running up against this warning when processing [the enum](https://github.com/gtiwari333/openrewrite-groovy-bug/blob/e43488440993271af1cd5b38efa7335c9cc90463/src/main/groovy/com/example/demo/Status.groovy#L3-L13).
https://github.com/openrewrite/rewrite/blob/734c9651b311a3df67e002ed174ebfc931a3c691/rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java#L357-L361

We can replicate this on a smaller scale by adding this test to 
https://github.com/openrewrite/rewrite/blob/769f6de46e2e3d711c495feb82e7e5e0f2d889c9/rewrite-groovy/src/test/java/org/openrewrite/groovy/format/AutoFormatVisitorTest.java#L25
```java
@Test
@Issue("https://github.com/openrewrite/rewrite/issues/4252")
void skipEnum() {
    rewriteRun(
      groovy(
        """
          package com.example.demo

          enum Status {
              WaitingToBeProcessed,
              InProcess,
              Complete,
              Failed
          }
          """
      )
    );
}
```

**Comment by timtebeek** [comment]
There's a hint in `visitEnumField` on how this could be achieved; you're welcome to give this a go if you'd like. It'd be kind of hard to fit in for me at this moment; we'd mostly added Groovy support for Gradle, such that enums or running autoformat there are rare, which is why you're only encountering this now.

**Comment by greg-at-moderne** [comment]
OSS repro ;)
https://github.com/openrewrite/rewrite/blob/f617e5a096424fe4af7881345d025682cf1717d5/rewrite-groovy/src/test/resources/GroovyTypeGoat.groovy#L36

**Comment by timtebeek** [comment]
PRs
- https://github.com/openrewrite/rewrite/pull/5781
- https://github.com/openrewrite/rewrite/pull/5802
