### ISSUE TITLE
OpenRewrite still fails on Java 23

### ISSUE THREAD

**Issue by triceo** [openrewrite/rewrite#4534]
Using the latest version of OpenRewrite (incl. #4516), I get the following exception:

    Caused by: java.lang.AssertionError: Failed to parse sources or run recipe
	at org.openrewrite.test.RewriteTest.lambda$defaultExecutionContext$14(RewriteTest.java:631)
	at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convert(ReloadableJava17ParserVisitor.java:1692)
	at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convert(ReloadableJava17ParserVisitor.java:1698)
	at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convertAll(ReloadableJava17ParserVisitor.java:1734)
	at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitCompilationUnit(ReloadableJava17ParserVisitor.java:551)
	at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitCompilationUnit(ReloadableJava17ParserVisitor.java:73)
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:625)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
	at org.openrewrite.java.isolated.ReloadableJava17Parser.lambda$parseInputs$0(ReloadableJava17Parser.java:166)
	... 16 more
    Caused by: org.openrewrite.java.JavaParsingException: Failed to convert for the following cursor stack:--- BEGIN PATH ---
        JCCompilationUnit(sourceFile = test.java)
    --- END PATH ---

	... 24 more
    Caused by: java.lang.NoSuchMethodError: 'com.sun.tools.javac.tree.DCTree$DCDocComment com.sun.tools.javac.tree.DocCommentTable.getCommentTree(com.sun.tools.javac.tree.JCTree)'
	at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convert(ReloadableJava17ParserVisitor.java:1669)
	... 23 more

To reproduce:

1. Clone https://github.com/TimefoldAI/timefold-solver
2. `mvn clean install -Dquickly`
3. `cd migration`
4. `mvn test`
5. See failing tests.

No tests are failing on either JDK 17, 21 or 22.

**Comment by timtebeek** [comment]
hi @triceo, Thanks for the update! #4516 Had changed our Java 21 parser, whereas your stacktrace for some reason is picking up the Java 17 parser. I've backported the fix to our Java 17 parser as well in 1e4a8d9468eb0e1a28b3164c192674562123c7a5, just to get you unblocked. Likely the proper fix is to [add our Java 21 parser to the Maven plugin](https://github.com/openrewrite/rewrite-maven-plugin/blob/acb511d312ee972c407ad04e08a795db3366b217/pom.xml#L164-L179).

**Comment by triceo** [comment]
Thank you, @timtebeek! I'll validate when a release is out.

**Comment by Col-E** [comment]
Confirming I've also encountered this stacktrace on Java 23

```
java.lang.NoSuchMethodError: 'com.sun.tools.javac.tree.DCTree$DCDocComment com.sun.tools.javac.tree.DocCommentTable.getCommentTree(com.sun.tools.javac.tree.JCTree)'
  org.openrewrite.java.isolated.ReloadableJava21ParserVisitor.convert(ReloadableJava21ParserVisitor.java:1667)
  org.openrewrite.java.isolated.ReloadableJava21ParserVisitor.visitCompilationUnit(ReloadableJava21ParserVisitor.java:538)
  org.openrewrite.java.isolated.ReloadableJava21ParserVisitor.visitCompilationUnit(ReloadableJava21ParserVisitor.java:74)
  com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:625)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
```
