### ISSUE TITLE
HCL Parser does not accept percent sign (%) in String literals

### ISSUE THREAD

**Issue by mccartney** [openrewrite/rewrite#4601]
## What is the smallest, simplest way to reproduce the problem?
```
    @Test
    void percentSignInStringLiteral() {
        rewriteRun(
          hcl(
            """
              locals {
                hello = "no alcohol %"
              }
              """
          )
        );
    }
```

## What is the full stack trace of any errors you encountered?
```
[...]
Caused by: org.openrewrite.hcl.HclParsingException: Syntax error in file.tf at line 2:24 token recognition error at: '\n'.
	at org.openrewrite.hcl.HclParser$ForwardingErrorListener.syntaxError(HclParser.java:105)
	... 132 more
Caused by: LexerNoViableAltException('\n')
	at org.antlr.v4.runtime.atn.LexerATNSimulator.failOrAccept(LexerATNSimulator.java:309)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.execATN(LexerATNSimulator.java:230)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.match(LexerATNSimulator.java:114)
	at org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:141)
	... 129 more
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

No opinion yet. I haven't looked at the possible fix yet.

**Comment by timtebeek** [comment]
Thanks for the report @mccartney ! That's sure surprising. 🤔 Appreciate the runnable example.
No idea why from a quick look at the ANTLR spec, although I'm certainly no expert there. Did you explore a cause/fix?

**Comment by timtebeek** [comment]
Looking at the spec it seems only `%{` would be special, and escaped as `%%{`. Then `%` by itself in a string ought to be fine.
https://github.com/hashicorp/hcl/blob/main/hclsyntax/spec.md
