### ISSUE TITLE
HCL Parser does not accept a comment as the last line in the file

### ISSUE THREAD

**Issue by mccartney** [openrewrite/rewrite#4611]
## What is the smallest, simplest way to reproduce the problem?
```
    @Test
    void commentAsTheLastLine() {
        rewriteRun(
          hcl(
            """
              locals {
                a = 3
              }
              # Nice code, right?
            """
          )
        );
    }
```

## What is the full stack trace of any errors you encountered?
```
[...]
Caused by: org.openrewrite.hcl.HclParsingException: Syntax error in file.tf at line 4:0 token recognition error at: '# Nice code, right?'.
	at org.openrewrite.hcl.HclParser$ForwardingErrorListener.syntaxError(HclParser.java:105)
	... 130 more
Caused by: LexerNoViableAltException('#')
	at org.antlr.v4.runtime.atn.LexerATNSimulator.failOrAccept(LexerATNSimulator.java:309)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.execATN(LexerATNSimulator.java:230)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.match(LexerATNSimulator.java:114)
	at org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:141)
	... 127 more
```

**Comment by timtebeek** [comment]
hi @mccartney ; thanks for the report! This seems very similar to 
- https://github.com/openrewrite/rewrite/issues/4544

Let me see if the suggestion reported there also fixes this issue.

**Comment by timtebeek** [comment]
Sadly this needs work beyond what was done in #4616 ; Any help appreciated!

**Comment by rahul3509** [comment]
I can look into it.

**Comment by mccartney** [comment]
I suspect this has something to do with the `\n` at the end of this rule:
https://github.com/openrewrite/rewrite/blob/f6d17f4d5977c7e00f3b826ce16480d781c7fbd1/rewrite-hcl/src/main/antlr/HCLLexer.g4#L54

**Comment by rahul3509** [comment]
I was debugging the issue looks like 

https://github.com/openrewrite/rewrite/blob/f6d17f4d5977c7e00f3b826ce16480d781c7fbd1/rewrite-hcl/src/main/java/org/openrewrite/hcl/HclParser.java#L69

`visitConfigFile` function call is failing, Looking into it.

**Comment by rahul3509** [comment]
<img width="932" alt="Screenshot 2024-11-06 at 3 08 50 PM" src="https://github.com/user-attachments/assets/57e00f7a-d197-4e2b-a903-543c5ab04721">
<img width="1192" alt="Screenshot 2024-11-06 at 3 07 58 PM" src="https://github.com/user-attachments/assets/4fbd4984-8fc8-44f6-a645-7c26240e2001">

I have tested the grammar is alright it is parsing and tokenizing contents of input properly.

**Comment by mccartney** [comment]
Related discussion in Antlr group: https://groups.google.com/g/antlr-discussion/c/1mJ0n38Jf8c?pli=1
