### ISSUE TITLE
HCL Parser doesn't support escaping double quote sign in String literals

### ISSUE THREAD

**Issue by mccartney** [openrewrite/rewrite#4612]
## What is the smallest, simplest way to reproduce the problem?
```
    @Test
    void quoteEscaping() {
        rewriteRun(
          hcl(
            """
              locals {
                quotedText = "this is a double quote: \". Look at me"
              }
              """
          )
        );
    }
```

## What is the full stack trace of any errors you encountered?
```
[...]
Caused by: org.openrewrite.hcl.HclParsingException: Syntax error in file.tf at line 2:54 token recognition error at: '\n'.
	at org.openrewrite.hcl.HclParser$ForwardingErrorListener.syntaxError(HclParser.java:105)
	... 132 more
Caused by: LexerNoViableAltException('\n')
	at org.antlr.v4.runtime.atn.LexerATNSimulator.failOrAccept(LexerATNSimulator.java:309)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.execATN(LexerATNSimulator.java:230)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.match(LexerATNSimulator.java:114)
	at org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:141)
	... 129 more
```

## Context

AFAICT this is a valid Terraform/HCL file.
https://developer.hashicorp.com/terraform/language/expressions/strings#escape-sequences says this is the proper way of escaping the quote sign.

**Comment by mccartney** [comment]
Actually I think the description above is wrong. This line:
```
                quotedText = "this is a double quote: \". Look at me"
```
"renders" to:
```
                quotedText = "this is a double quote: ". Look at me"
```
in HCL.

The backslash is basically swallowed by Java as hinted by Intelli:
<img width="617" alt="image" src="https://github.com/user-attachments/assets/0e55c5f8-023f-4ef8-9d11-e83ea3b19539">

And if so, the HCL file provided in the test is not a valid Terraform/HCL file. And Rewrite is right when failing.
