### ISSUE TITLE
HCL Parser fails with a trailing dollar sign in String literal

### ISSUE THREAD

**Issue by mccartney** [openrewrite/rewrite#4613]
## What is the smallest, simplest way to reproduce the problem?
```
    void trailingDollarSign() {
        rewriteRun(
          hcl(
            """
              locals {
                regexp = "^(.*?)-monitoring$"
              }
              """
          )
        );
    }
```

## What is the full stack trace of any errors you encountered?
```
[...]
Caused by: org.openrewrite.hcl.HclParsingException: Syntax error in file.tf at line 2:31 token recognition error at: '\n'.
	at org.openrewrite.hcl.HclParser$ForwardingErrorListener.syntaxError(HclParser.java:105)
	... 132 more
Caused by: LexerNoViableAltException('\n')
	at org.antlr.v4.runtime.atn.LexerATNSimulator.failOrAccept(LexerATNSimulator.java:309)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.execATN(LexerATNSimulator.java:230)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.match(LexerATNSimulator.java:114)
	at org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:141)
	... 129 more
```

**Comment by mccartney** [comment]
My hunch is that it's because of this rule:
https://github.com/openrewrite/rewrite/blob/b21c0a46588cffb894fe938d4b22330611c82446/rewrite-hcl/src/main/antlr/HCLLexer.g4#L145
Which does allow dollar signs, but only if they are followed by some other character.
And no other rule allows for dollar signs.

**Comment by timtebeek** [comment]
Nice find! We have [some guidance here](https://github.com/openrewrite/rewrite/blob/v8.38.1/tools/language-parser-builder/README.md) on how to run the generator, but it's been a while for me as well; appreciate you diving in! 🙏🏻

**Comment by mccartney** [comment]
In case anyone is wondering, after editing the `.g4` files, it's enough to run `./gradlew rewrite-hcl:generateAntlrSources`.

The linked document has fuller context for setting up new lexer/parser for a new language.
