### ISSUE TITLE
NPE in JavaPrinter.visitRightPadded

### ISSUE THREAD

**Issue by klaraward** [openrewrite/rewrite#474]
When I made a custom format, specifically with this ImportLayoutStyle
```
    public static ImportLayoutStyle importLayout() {
        return ImportLayoutStyle.builder()
                                .classCountToUseStarImport(9999)
                                .nameCountToUseStarImport(9999)
                                .importStaticAllOthers()
                               .blankLine()
                                .importAllOthers()
                                .blankLine()
                                .build();
    }
```
if I include the blankLine between the two import methods, I get the following NPE (otherwise it works fine, except I of course lack the blank line) :

```
Exception in thread "main" java.lang.NullPointerException
	at org.openrewrite.java.JavaPrinter.visitRightPadded(JavaPrinter.java:83)
	at org.openrewrite.java.JavaPrinter.visitContainer(JavaPrinter.java:98)
	at org.openrewrite.java.JavaPrinter.visitMethodInvocation(JavaPrinter.java:737)
	at org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3145)
	at org.openrewrite.java.tree.J.accept(J.java:57)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:140)
	at org.openrewrite.java.JavaPrinter.visit(JavaPrinter.java:64)
	at org.openrewrite.java.JavaPrinter.visitRightPadded(JavaPrinter.java:83)
...
```

I tried to fix it by tweaking `blankLines` but no success so far.

Using version 7.1.0

**Comment by jkschneider** [comment]
Thanks for the report @klaraward !

**Comment by jkschneider** [comment]
@klaraward Could you see the attached passing test in a29f80c and suggest what's different about your imports when it fails? Thanks!
