### ISSUE TITLE
Compatibility with Kotlin 2.x

### ISSUE THREAD

**Issue by Hyunk3l** [openrewrite/rewrite#5128]
hei team

I'm trying to use `rewriteRun`<https://github.com/Hyunk3l/ecommerce> in this public project I've (kotlin 2.1, java 17, etc.)

```
rewrite {
    activeRecipe(
        "org.openrewrite.java.OrderImports",
    )
}
```

I'm trying with this recipe and this is the error I get
```
'org.jetbrains.kotlin.fir.session.environment.AbstractProjectFileSearchScope org.jetbrains.kotlin.cli.jvm.compiler.VfsBasedProjectEnvironment.getSearchScopeByPsiFiles(java.lang.Iterable, boolean)'
```

I suspect it's because of Kotlin 2.1.. so I downgraded it to 2.0.20 but
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':shopping:rewriteRun'.
&gt; 'org.jetbrains.kotlin.fir.FirSession org.jetbrains.kotlin.fir.session.FirSessionFactoryHelper.createSessionWithDependencies(org.jetbrains.kotlin.name.Name, org.jetbrains.kotlin.platform.TargetPlatform, org.jetbrains.kotlin.resolve.PlatformDependentAnalyzerServices, org.jetbrains.kotlin.fir.java.FirProjectSessionProvider, org.jetbrains.kotlin.fir.session.environment.AbstractProjectEnvironment, org.jetbrains.kotlin.config.LanguageVersionSettings, org.jetbrains.kotlin.fir.session.environment.AbstractProjectFileSearchScope, org.jetbrains.kotlin.fir.session.environment.AbstractProjectFileSearchScope, org.jetbrains.kotlin.incremental.components.LookupTracker, org.jetbrains.kotlin.incremental.components.EnumWhenTracker, org.jetbrains.kotlin.incremental.components.ImportTracker, org.jetbrains.kotlin.fir.session.IncrementalCompilationContext, java.util.List, boolean, kotlin.jvm.functions.Function1, kotlin.jvm.functions.Function1)'
```

[Slack Message](https://rewriteoss.slack.com/archives/C01A843MWG5/p1733441159712739?thread_ts=1733441159.712739&cid=C01A843MWG5)

**Comment by idanakav** [comment]
@barbulescu I'm curious to know if there are any remaining blockers to ship 2.1.x?

**Comment by timtebeek** [comment]
Thanks for your interest @idanakav ! As also indicated on that PR we've since moved rewrite-kotlin into this repository
- https://github.com/openrewrite/rewrite-kotlin/pull/627#issuecomment-2720704989

That means the same changes as seen there should now target this repository instead; any help there welcome! :)

**Comment by barbulescu** [comment]
There are still few issues, but I need more time to understand both Kotlin FIR and OpenRewrite.

It would be great if anyone with this know-how can help here.

If not, I will continue next weekend.

**Comment by barbulescu** [comment]
I am blocked at the part where FirSession is created in KotlinParser.

I got a [suggestion](https://kotlinlang.slack.com/archives/C7L3JB43G/p1747033149595299?thread_ts=1746886540.255859&cid=C7L3JB43G), but it looks like there are a lot of changes on this area.

Can anybody help here?

**Comment by timtebeek** [comment]
@greg-at-moderne would you be able to help provide some guidance here? 🙏

**Comment by greg-at-moderne** [comment]
My knowledge of Kotlin is close to zero, but I am happy to help. I've just requested to join the Kotlin Lang Slack to read the context.

**Comment by barbulescu** [comment]
I had some progress and I am trying to fix `WrappingAndBracesTest:blockLevelStatements` test with this failure:

```
java.lang.IllegalStateException: LST contains missing or invalid type information
Identifier->Unary->Block->Block->ClassDeclaration->CompilationUnit
/*~~(Identifier type is missing or malformed)~~>*/n

	at org.openrewrite.kotlin.Assertions.assertValidTypes(Assertions.java:242)
	at org.openrewrite.kotlin.Assertions.validateTypes(Assertions.java:57)
```

I tried to debug but I get easily lost.

Is any strategy for finding the root cause of such an issue?

**Comment by timtebeek** [comment]
Hmm, quick answer from mobile seeing this now. The way I tend to go through is to first run the rest with coverage, and then from there set breakpoints on the paths I know are hit. In this case it looks like the type is missing on this ++ operator: 
https://github.com/openrewrite/rewrite/blob/2b9bc08784f7f7c0e265f268b783f55daba620fb/rewrite-java-test/src/test/java/org/openrewrite/java/format/WrappingAndBracesTest.java#L56

Is there any branch where we could maybe try to have a look as well? Not likely I'll get to it before Thursday with travel, but maybe Greg will have more ideas still.

**Comment by barbulescu** [comment]
I am working on main branch of my [fork](https://github.com/barbulescu/rewrite/tree/main).

**Comment by timtebeek** [comment]
Thanks! Feel free to open up an early draft PR; that makes it easier for folks to be aware and check out your work already.

I had a brief look here, but can't see much more beyond confirming that when we look up the type for `n` here it's returned as `null`, despite being present in `psiElementAssociations`. 🤔 
https://github.com/openrewrite/rewrite/blob/5b5b43d311c802f6524d0f2c80b941722ff9d077/rewrite-kotlin/src/main/java/org/openrewrite/kotlin/internal/KotlinTreeParserVisitor.java#L3088-L3092

**Comment by barbulescu** [comment]
- https://github.com/openrewrite/rewrite/pull/5575

**Comment by barbulescu** [comment]
`FirRegularClassSymbol` seems to not be handled in `KotlinTypeSignatureBuilder:signature`, but not clear yet how to handle.

Cannot find `ConeStubTypeForChainInference` anymore so not sure how to handle this either.

**Comment by timtebeek** [comment]
Linking the no-login-or-slack-required link to the Kotlin lang Slack here as well:
https://slack-chats.kotlinlang.org/t/28493795/what-is-the-recommended-way-to-migrate-firsessionfactoryhelp

> What is the recommended way to migrate FirSessionFactoryHelper.INSTANCE.createSessionWithDependencies when moving to Kotlin +2.1? The usage is in Openrewrite https://github.com/openrewrite/rewrite/blob/main/rewrite-kotlin/src/main/java/org/openrewrite/kotlin/KotlinParser.java#L475

> Most of production methods of session creation were migrated to the unified [SessionConstructionUtils.prepareSessions](https://github.com/JetBrains/kotlin/blob/33039871615dcab9a2a141c683a2fa328fffd6d4/compiler/cli/src/org/jetbrains/kotlin/cli/common/FirSessionConstructionUtils.kt#L343) utility.
The same file contains methods like prepareJsSessions and prepareNativeSessions for specific platforms.
Proper prepareJvmSessions is declared inside [JvmFrontendPipelinePhase](https://github.com/JetBrains/kotlin/blob/5850b533a38a9beed0d06992c418c9c039d30ad1/compiler/cli/src/org/jetbrains/kotlin/cli/pipeline/jvm/JvmFrontendPipelinePhase.kt#L314) and I expect that utilities for other platforms would be eventually moved to similar phases too in the future

**Comment by barbulescu** [comment]
Solved the ++ operator handling and next is adding support for `FirResolvedArgumentList`.

29 more tests to fix.

**Comment by barbulescu** [comment]
I get many failures like this one:

```
org.opentest4j.AssertionFailedError: [When parsing and printing the source code back to text without modifications, the printed source didn't match the original source code. This means there is a bug in the parser implementation itself. Please open an issue to report this, providing a sample of the code that generated this error. "openRewriteFile.kt":
diff --git a/openRewriteFile.kt b/openRewriteFile.kt
index cbf907e..8ce565a 100644
--- a/openRewriteFile.kt
+++ b/openRewriteFile.kt
@@ -1,2 +1,2 @@ 
 val String .  extension   :   Any
-    get (  )  =  ""
\ No newline at end of file
+    get(  )  =  ""
\ No newline at end of file
] 
expected: 
  "val String .  extension   :   Any
      get (  )  =  """
 but was: 
  "val String .  extension   :   Any
      get(  )  =  """
```

Any idea where in parsing I should look for the issue?

**Comment by timtebeek** [comment]
Hi @barbulescu ; copying a link to the (likely) respective test here:
https://github.com/openrewrite/rewrite/blob/4fa4491a4b030488c3f0aa7289a1219ac6c32614/rewrite-kotlin/src/test/java/org/openrewrite/kotlin/format/SpacesTest.java#L2748-L2762

If I change that test slightly I can jump in with the debugger to explore how that's defined on your branch:
```java
    @Test
    void extensionProperty() {
        rewriteRun(
          kotlin(
            """
              val String .  extension   :   Any
                  get(  )  =  ""
              """,
            """
              val String.extension: Any
                  get() =  ""
              """,
            spec -> spec
              .beforeRecipe(cu -> {
                TreeVisitingPrinter.printTreeAll(cu); // Set a breakpoint here
              })
              .afterRecipe(cu -> {
                TreeVisitingPrinter.printTreeAll(cu);
            })
          )
        );
    }
```
## [Your branch](https://github.com/openrewrite/rewrite/pull/5575)
![Image](https://github.com/user-attachments/assets/c801cf95-5157-47fd-b5ca-61c48ee08fa6)

## Main branch

![Image](https://github.com/user-attachments/assets/4df52211-50fd-40c4-82fa-10407c9db5b1)

## Difference
If you compare the two closely, you'll find that the MethodDeclaration field parameters is a JContainer in both, but only on the main branch has a before for a single space, whereas on your branch that's empty. That then leads to the print inequality on the test input, and a failure to start running the associated test recipe. I hope that helps!

**Comment by barbulescu** [comment]
`beforeRecipe` is not called for me because `assertContentEquals` fails before that. Is any other way to see the tree before this assertion fails?

**Comment by timtebeek** [comment]
> `beforeRecipe` is not called for me because `assertContentEquals` fails before that. Is any other way to see the tree before this assertion fails?

Hi @barbulescu ; that's a bit awkward indeed; while you could set a breakpoint and inspect the value in a debugger, perhaps this would be the more sympathetic change in the framework to allow you get inspect the value before it's rejected by validation:
- https://github.com/openrewrite/rewrite/pull/5888

Let's see if my colleagues agree, as I've had this desire in the past as well to inspect the LST elements, as opposed to just their text.

**Comment by timtebeek** [comment]
Hi all;  we've just merged a PR that brings Kotlin v2 parser support
- https://github.com/openrewrite/rewrite/pull/6766
