### ISSUE TITLE
RecipeDiagnosticTest JsonParseException

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite#614]
RecpieDiagnosticTest fails with JsonParseException.

Example test:
```java
package org.openrewrite.java.spring.org.openrewrite.java.spring

import org.junit.jupiter.api.Test
import org.openrewrite.RecipeDiagnosticTest
import org.openrewrite.java.testing.junit5.AssertToAssertions

class SpringRecipeDiagnosticTest : RecipeDiagnosticTest() {
    @Test
    fun testAssertionsIsue() = assertUnchanged(
        recipe = AssertToAssertions(),
        "https://api.moderne.io:443/worker/cmVjaXBld29ya2VyLXByb2QtdjA2NC1jcmox/ast/file/spring-projects%3Aspring-batch/6b4c91632195dff3a5ac6059c7c69ac1063fad60/c3ByaW5nLWJhdGNoLXRlc3Qvc3JjL3Rlc3QvamF2YS9vcmcvc3ByaW5nZnJhbWV3b3JrL2JhdGNoL3Rlc3QvSm9iU2NvcGVUZXN0RXhlY3V0aW9uTGlzdGVuZXJJbnRlZ3JhdGlvblRlc3RzLmphdmE=",
        "Bearer ..."
    )
}
```

Error log:
```log
java.io.UncheckedIOException: com.fasterxml.jackson.core.JsonParseException: Invalid shared text value reference 959; only got 0 names in buffer (invalid content)
 at [Source: (okio.RealBufferedSource$inputStream$1); line: -1, column: 6]

	at org.openrewrite.TreeSerializer.read(TreeSerializer.java:123)
	at org.openrewrite.RecipeDiagnosticTest.assertUnchanged(RecipeDiagnosticTest.kt:97)
	at org.openrewrite.java.spring.org.openrewrite.java.spring.SpringRecipeDiagnosticTest.testSomething(SpringRecipeDiagnosticTest.kt:10)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	...
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: com.fasterxml.jackson.core.JsonParseException: Invalid shared text value reference 959; only got 0 names in buffer (invalid content)
 at [Source: (okio.RealBufferedSource$inputStream$1); line: -1, column: 6]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2337)
```

**Comment by jkschneider** [comment]
@pway99 Was the response body empty?

**Comment by pway99** [comment]
@jkschneider no the response body is not empty.
![image](https://user-images.githubusercontent.com/22326988/121039377-e276e880-c765-11eb-8919-03b8f2771e49.png)

**Comment by pway99** [comment]
issue has been resolved
