### ISSUE TITLE
Wildcard import unfolded into more than one import with same UUIDs

### ISSUE THREAD

**Issue by BoykoAlex** [openrewrite/rewrite#781]
This one took time to figure out but is a cause of many test failures on our side:

See this test:

```kotlin
    @Test
    fun removeWithWildcard(jp: JavaParser) = assertChanged(
        jp,
        recipe = removeImport("java.util.Collection")
            .doNext(ChangeType("java.util.List", "java.util.Collection"))
        ,
        before = """
package a;            

import java.util.*;

public class A {
    Set s;
    List l;
}
""",
        after = """
package a;            

import java.util.Collection;
import java.util.Set;

public class A {
    Set s;
    Collection l;
}
"""
    )
```

import ending with `*` is unfolded into 2 import for List and Set both of these have same UUID, then removing one of these imports with same UUID results in exception coming from:

```
at org.openrewrite.java.tree.JRightPadded.withElements(JRightPadded.java:141)
	at org.openrewrite.java.tree.J$CompilationUnit.withImports(J.java:1139)
```

If I change the following method in `RemoveImport` like follows (withId appended):
```java
    private Object unfoldStarImport(J.Import starImport, Set<String> otherImportsUsed) {
        List<J.Import> unfoldedImports = new ArrayList<>(otherImportsUsed.size());
        int i = 0;
        for (String other : otherImportsUsed) {
            J.Import unfolded = starImport.withQualid(starImport.getQualid().withName(starImport
                    .getQualid().getName().withName(other))).withId(Tree.randomId());
            unfoldedImports.add(i++ == 0 ? unfolded : unfolded.withPrefix(Space.format("\n")));
        }
        return unfoldedImports;
    }
```

Everything starts working... not sure if old id needs to be kept...

**Comment by traceyyoshima** [comment]
Thanks for creating this issue! In this case the old import element is being replaced, so it's reasonable to create new ids for each unfolded import. Taking a look
