### ISSUE TITLE
Parsing Issue

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite#881]
Discovered during ingest of micronaut-core on this file:

https://github.com/micronaut-projects/micronaut-core/blob/2.5.x/management/src/main/java/io/micronaut/management/endpoint/loggers/impl/DefaultLoggersManager.java

The error :

```
09:28:41.859 [main] ERROR i.m.ingest.parse.GradleProjectParser - Error parsing
org.openrewrite.java.JavaParsingException: Failed to convert for the following cursor stack:--- BEGIN PATH ---
JCCompilationUnit(sourceFile = /Users/tyler.vangorder/work/sample-repos/micronaut-core/management/src/main/java/io/micronaut/management/endpoint/loggers/impl/DefaultLoggersManager.java)
JCClassDecl(name = DefaultLoggersManager, line = 35)
JCMethodDecl(line = 67)
JCTypeApply(line = 67)
--- END PATH ---

Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 3193
	at java.lang.String.substring(String.java:1963)
	at org.openrewrite.java.ReloadableJava8ParserVisitor.convert(ReloadableJava8ParserVisitor.java:1424)

```

**Comment by tkvangorder** [comment]
I don't envision us making the required changes to support this.
