### ISSUE TITLE
Javadoc parsing error with multi-line text and @throws

### ISSUE THREAD

**Issue by csemrau** [openrewrite/rewrite#976]
```
import java.io.IOException;

public class ActionTestHelper {

    /**
     * Delete the stop file if it exists.
     * This is necessary if the stop file was not deleted during the test.
     *
     * @throws IOException if the stop file exists, but could not be deleted.
     */
    public static void cleanupStopFile() throws IOException {
    }
}
```

**Comment by csemrau** [comment]
Observed this one with the current `main` branch and a self-built snapshot version.

**Comment by jkschneider** [comment]
Thanks @csemrau :). Introducing Javadocs has been tough -- working through a few more issues prior to 7.13.0 going out.

**Comment by jkschneider** [comment]
Looks like this was fixed in one of the last commits.

**Comment by csemrau** [comment]
I ensured to use the most recent version (based on commit `be8f657f6da732d1e77e956b5f0a205e4a9bc939`), and can reproduce the parse error in a dummy project with Java 11.

I locally added a corresponding unit test to rewrite-java. It succeeds with the Java 8 test subclass. I did not manage to run the Java 11 test subclass though. I tried running the tests from IntelliJ.

**Comment by csemrau** [comment]
I checked out the current `main` branch once more, and extended the exception with more details:

        int endIndex = source.indexOf(delim, cursor);
        if (endIndex < 0) {
            throw new IllegalStateException("Expected to be able to find " + delim + " in \"" +
                    source.substring(cursor).replace("\\", "\\\\").replace("\n", "\\n").replace("\r", "\\r").replace("\"", "\\\"") + "\"");
        }

I published to maven local and ran this command on a dummy project containing only the file above (with no-daemon because otherwise I'd need to stop the daemon each time I publish the rewrite libraries to maven local):

    gradlew rewriteDryRun --no-daemon --stacktrace -DactiveRecipe=org.openrewrite.java.RemoveUnusedImports

I got this exception for the file above formatted with Unix linebreaks:

    java.lang.IllegalStateException: Expected to be able to find @exception in "he test.\r     *\r     * @throws IOException if the stop file exists, but could not be deleted.\r     "

With Windows linebreaks, I got this exception instead:

    java.lang.IllegalStateException: Expected to be able to find @exception in ".\r\n\r\n @throws IOException if the stop file exists, but could not be deleted.\r"

Seems that `Java11JavadocVisitor.visitThrows` expects the `cursor` to be at the `@throws`, but it is not, so it starts looking for `@exception` instead of `@throws`.

For reference, the original exception, as of release 7.13.0, is this:

    Caused by: java.lang.IllegalStateException: Expected to be able to find @exception
        at org.openrewrite.java.Java11JavadocVisitor.sourceBefore(Java11JavadocVisitor.java:859)
        at org.openrewrite.java.Java11JavadocVisitor.visitThrows(Java11JavadocVisitor.java:781)
        at org.openrewrite.java.Java11JavadocVisitor.visitThrows(Java11JavadocVisitor.java:46)
        at jdk.compiler/com.sun.tools.javac.tree.DCTree$DCThrows.accept(DCTree.java:932)
        at jdk.compiler/com.sun.source.util.DocTreeScanner.scan(DocTreeScanner.java:79)
        at org.openrewrite.java.Java11JavadocVisitor.visitDocComment(Java11JavadocVisitor.java:305)
        at org.openrewrite.java.Java11JavadocVisitor.visitDocComment(Java11JavadocVisitor.java:46)
        at jdk.compiler/com.sun.tools.javac.tree.DCTree$DCDocComment.accept(DCTree.java:138)
        at jdk.compiler/com.sun.source.util.DocTreeScanner.scan(DocTreeScanner.java:79)
        at org.openrewrite.java.Java11ParserVisitor.formatWithCommentTree(Java11ParserVisitor.java:1936)
        at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1434)

**Comment by csemrau** [comment]
This exception only occurs with Java 11, not with Java 8.
